"""add ai_assistant tables

Revision ID: 0e73e2b0dc65
Revises: 15eaeb5cfdfb
Create Date: 2026-04-12 16:48:49.877240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0e73e2b0dc65'
down_revision: Union[str, None] = '15eaeb5cfdfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_assistant_group',
    sa.Column('group_id', sa.String(length=100), nullable=False, comment='外部系统群组ID'),
    sa.Column('group_name', sa.String(length=200), nullable=False, comment='群组名称'),
    sa.Column('is_group', sa.Boolean(), nullable=False, comment='是否群聊'),
    sa.Column('trigger_word', sa.String(length=50), nullable=False, comment='触发词'),
    sa.Column('requires_trigger', sa.Boolean(), nullable=False, comment='是否需要触发词'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('last_message_time', sa.DateTime(), nullable=True, comment='最后消息时间'),
    sa.Column('id', sa.String(length=21), nullable=False, comment='主键ID(NanoId)'),
    sa.Column('sort', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='是否删除'),
    sa.Column('sys_create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('sys_update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('sys_creator_id', sa.String(length=21), nullable=True, comment='创建人ID（逻辑外键关联core_user）'),
    sa.Column('sys_modifier_id', sa.String(length=21), nullable=True, comment='修改人ID（逻辑外键关联core_user）'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_assistant_group_group_id'), 'ai_assistant_group', ['group_id'], unique=True)
    op.create_index(op.f('ix_ai_assistant_group_is_active'), 'ai_assistant_group', ['is_active'], unique=False)
    op.create_index(op.f('ix_ai_assistant_group_is_deleted'), 'ai_assistant_group', ['is_deleted'], unique=False)
    op.create_table('ai_assistant_message',
    sa.Column('session_id', sa.String(length=36), nullable=False, comment='关联会话ID'),
    sa.Column('message_type', sa.Integer(), nullable=False, comment='消息类型: 0-用户, 1-AI'),
    sa.Column('sender_id', sa.String(length=100), nullable=False, comment='发送者ID'),
    sa.Column('sender_name', sa.String(length=100), nullable=True, comment='发送者名称'),
    sa.Column('content', sa.Text(), nullable=False, comment='消息内容'),
    sa.Column('nanoclaw_message_id', sa.String(length=100), nullable=True, comment='NanoClaw消息ID'),
    sa.Column('reply_to_message_id', sa.String(length=100), nullable=True, comment='回复消息ID'),
    sa.Column('send_time', sa.DateTime(), nullable=False, comment='发送时间'),
    sa.Column('receive_time', sa.DateTime(), nullable=True, comment='接收时间'),
    sa.Column('is_context_recovery', sa.Boolean(), nullable=False, comment='是否上下文恢复消息'),
    sa.Column('id', sa.String(length=21), nullable=False, comment='主键ID(NanoId)'),
    sa.Column('sort', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='是否删除'),
    sa.Column('sys_create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('sys_update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('sys_creator_id', sa.String(length=21), nullable=True, comment='创建人ID（逻辑外键关联core_user）'),
    sa.Column('sys_modifier_id', sa.String(length=21), nullable=True, comment='修改人ID（逻辑外键关联core_user）'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_assistant_message_is_deleted'), 'ai_assistant_message', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_ai_assistant_message_message_type'), 'ai_assistant_message', ['message_type'], unique=False)
    op.create_index(op.f('ix_ai_assistant_message_session_id'), 'ai_assistant_message', ['session_id'], unique=False)
    op.create_table('ai_assistant_session',
    sa.Column('group_id', sa.String(length=100), nullable=False, comment='关联群组ID'),
    sa.Column('chat_id', sa.String(length=150), nullable=False, comment='NanoClaw chat_id'),
    sa.Column('session_name', sa.String(length=200), nullable=True, comment='会话名称'),
    sa.Column('message_count', sa.Integer(), nullable=False, comment='消息计数'),
    sa.Column('status', sa.Integer(), nullable=False, comment='状态: 0-活跃, 1-已关闭, 2-已清除'),
    sa.Column('start_time', sa.DateTime(), nullable=False, comment='开始时间'),
    sa.Column('last_message_time', sa.DateTime(), nullable=False, comment='最后消息时间'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否活跃'),
    sa.Column('id', sa.String(length=21), nullable=False, comment='主键ID(NanoId)'),
    sa.Column('sort', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='是否删除'),
    sa.Column('sys_create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('sys_update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('sys_creator_id', sa.String(length=21), nullable=True, comment='创建人ID（逻辑外键关联core_user）'),
    sa.Column('sys_modifier_id', sa.String(length=21), nullable=True, comment='修改人ID（逻辑外键关联core_user）'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_assistant_session_chat_id'), 'ai_assistant_session', ['chat_id'], unique=True)
    op.create_index(op.f('ix_ai_assistant_session_group_id'), 'ai_assistant_session', ['group_id'], unique=False)
    op.create_index(op.f('ix_ai_assistant_session_is_active'), 'ai_assistant_session', ['is_active'], unique=False)
    op.create_index(op.f('ix_ai_assistant_session_is_deleted'), 'ai_assistant_session', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_ai_assistant_session_status'), 'ai_assistant_session', ['status'], unique=False)
    op.alter_column('worker_upgrade_config', 'device_type',
               existing_type=sa.VARCHAR(length=20),
               comment='设备类型: windows/mac',
               existing_nullable=False)
    op.alter_column('worker_upgrade_config', 'version',
               existing_type=sa.VARCHAR(length=32),
               comment='目标版本号(时间戳格式)',
               existing_nullable=False)
    op.alter_column('worker_upgrade_config', 'download_url',
               existing_type=sa.VARCHAR(length=512),
               comment='安装包下载地址',
               existing_nullable=False)
    op.alter_column('worker_upgrade_config', 'note',
               existing_type=sa.TEXT(),
               comment='备注',
               existing_nullable=True)
    op.alter_column('worker_upgrade_config', 'id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=21),
               comment='主键ID(NanoId)',
               existing_nullable=False)
    op.alter_column('worker_upgrade_config', 'sort',
               existing_type=sa.INTEGER(),
               comment='排序',
               existing_nullable=True)
    op.alter_column('worker_upgrade_config', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               comment='是否删除',
               existing_nullable=True)
    op.alter_column('worker_upgrade_config', 'sys_create_datetime',
               existing_type=postgresql.TIMESTAMP(),
               comment='创建时间',
               existing_nullable=True)
    op.alter_column('worker_upgrade_config', 'sys_update_datetime',
               existing_type=postgresql.TIMESTAMP(),
               comment='更新时间',
               existing_nullable=True)
    op.alter_column('worker_upgrade_config', 'sys_creator_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=21),
               comment='创建人ID（逻辑外键关联core_user）',
               existing_nullable=True)
    op.alter_column('worker_upgrade_config', 'sys_modifier_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=21),
               comment='修改人ID（逻辑外键关联core_user）',
               existing_nullable=True)
    op.create_index(op.f('ix_worker_upgrade_config_is_deleted'), 'worker_upgrade_config', ['is_deleted'], unique=False)
    op.alter_column('worker_upgrade_queue', 'machine_id',
               existing_type=sa.VARCHAR(length=36),
               comment='机器ID',
               existing_nullable=False)
    op.alter_column('worker_upgrade_queue', 'target_version',
               existing_type=sa.VARCHAR(length=32),
               comment='目标版本号',
               existing_nullable=False)
    op.alter_column('worker_upgrade_queue', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='状态: waiting/completed/failed',
               existing_nullable=False)
    op.alter_column('worker_upgrade_queue', 'device_type',
               existing_type=sa.VARCHAR(length=20),
               comment='设备类型',
               existing_nullable=False)
    op.alter_column('worker_upgrade_queue', 'namespace',
               existing_type=sa.VARCHAR(length=64),
               comment='机器分类',
               existing_nullable=False)
    op.alter_column('worker_upgrade_queue', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='入队时间',
               existing_nullable=False)
    op.alter_column('worker_upgrade_queue', 'completed_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='完成时间',
               existing_nullable=True)
    op.alter_column('worker_upgrade_queue', 'id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=21),
               comment='主键ID(NanoId)',
               existing_nullable=False)
    op.alter_column('worker_upgrade_queue', 'sort',
               existing_type=sa.INTEGER(),
               comment='排序',
               existing_nullable=True)
    op.alter_column('worker_upgrade_queue', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               comment='是否删除',
               existing_nullable=True)
    op.alter_column('worker_upgrade_queue', 'sys_create_datetime',
               existing_type=postgresql.TIMESTAMP(),
               comment='创建时间',
               existing_nullable=True)
    op.alter_column('worker_upgrade_queue', 'sys_update_datetime',
               existing_type=postgresql.TIMESTAMP(),
               comment='更新时间',
               existing_nullable=True)
    op.alter_column('worker_upgrade_queue', 'sys_creator_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=21),
               comment='创建人ID（逻辑外键关联core_user）',
               existing_nullable=True)
    op.alter_column('worker_upgrade_queue', 'sys_modifier_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=21),
               comment='修改人ID（逻辑外键关联core_user）',
               existing_nullable=True)
    op.drop_index('ix_upgrade_queue_machine_id', table_name='worker_upgrade_queue')
    op.create_index(op.f('ix_worker_upgrade_queue_is_deleted'), 'worker_upgrade_queue', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_worker_upgrade_queue_machine_id'), 'worker_upgrade_queue', ['machine_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_worker_upgrade_queue_machine_id'), table_name='worker_upgrade_queue')
    op.drop_index(op.f('ix_worker_upgrade_queue_is_deleted'), table_name='worker_upgrade_queue')
    op.create_index('ix_upgrade_queue_machine_id', 'worker_upgrade_queue', ['machine_id'], unique=False)
    op.alter_column('worker_upgrade_queue', 'sys_modifier_id',
               existing_type=sa.String(length=21),
               type_=sa.VARCHAR(length=36),
               comment=None,
               existing_comment='修改人ID（逻辑外键关联core_user）',
               existing_nullable=True)
    op.alter_column('worker_upgrade_queue', 'sys_creator_id',
               existing_type=sa.String(length=21),
               type_=sa.VARCHAR(length=36),
               comment=None,
               existing_comment='创建人ID（逻辑外键关联core_user）',
               existing_nullable=True)
    op.alter_column('worker_upgrade_queue', 'sys_update_datetime',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=True)
    op.alter_column('worker_upgrade_queue', 'sys_create_datetime',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=True)
    op.alter_column('worker_upgrade_queue', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否删除',
               existing_nullable=True)
    op.alter_column('worker_upgrade_queue', 'sort',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='排序',
               existing_nullable=True)
    op.alter_column('worker_upgrade_queue', 'id',
               existing_type=sa.String(length=21),
               type_=sa.VARCHAR(length=36),
               comment=None,
               existing_comment='主键ID(NanoId)',
               existing_nullable=False)
    op.alter_column('worker_upgrade_queue', 'completed_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='完成时间',
               existing_nullable=True)
    op.alter_column('worker_upgrade_queue', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='入队时间',
               existing_nullable=False)
    op.alter_column('worker_upgrade_queue', 'namespace',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='机器分类',
               existing_nullable=False)
    op.alter_column('worker_upgrade_queue', 'device_type',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='设备类型',
               existing_nullable=False)
    op.alter_column('worker_upgrade_queue', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='状态: waiting/completed/failed',
               existing_nullable=False)
    op.alter_column('worker_upgrade_queue', 'target_version',
               existing_type=sa.VARCHAR(length=32),
               comment=None,
               existing_comment='目标版本号',
               existing_nullable=False)
    op.alter_column('worker_upgrade_queue', 'machine_id',
               existing_type=sa.VARCHAR(length=36),
               comment=None,
               existing_comment='机器ID',
               existing_nullable=False)
    op.drop_index(op.f('ix_worker_upgrade_config_is_deleted'), table_name='worker_upgrade_config')
    op.alter_column('worker_upgrade_config', 'sys_modifier_id',
               existing_type=sa.String(length=21),
               type_=sa.VARCHAR(length=36),
               comment=None,
               existing_comment='修改人ID（逻辑外键关联core_user）',
               existing_nullable=True)
    op.alter_column('worker_upgrade_config', 'sys_creator_id',
               existing_type=sa.String(length=21),
               type_=sa.VARCHAR(length=36),
               comment=None,
               existing_comment='创建人ID（逻辑外键关联core_user）',
               existing_nullable=True)
    op.alter_column('worker_upgrade_config', 'sys_update_datetime',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=True)
    op.alter_column('worker_upgrade_config', 'sys_create_datetime',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=True)
    op.alter_column('worker_upgrade_config', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否删除',
               existing_nullable=True)
    op.alter_column('worker_upgrade_config', 'sort',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='排序',
               existing_nullable=True)
    op.alter_column('worker_upgrade_config', 'id',
               existing_type=sa.String(length=21),
               type_=sa.VARCHAR(length=36),
               comment=None,
               existing_comment='主键ID(NanoId)',
               existing_nullable=False)
    op.alter_column('worker_upgrade_config', 'note',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='备注',
               existing_nullable=True)
    op.alter_column('worker_upgrade_config', 'download_url',
               existing_type=sa.VARCHAR(length=512),
               comment=None,
               existing_comment='安装包下载地址',
               existing_nullable=False)
    op.alter_column('worker_upgrade_config', 'version',
               existing_type=sa.VARCHAR(length=32),
               comment=None,
               existing_comment='目标版本号(时间戳格式)',
               existing_nullable=False)
    op.alter_column('worker_upgrade_config', 'device_type',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='设备类型: windows/mac',
               existing_nullable=False)
    op.drop_index(op.f('ix_ai_assistant_session_status'), table_name='ai_assistant_session')
    op.drop_index(op.f('ix_ai_assistant_session_is_deleted'), table_name='ai_assistant_session')
    op.drop_index(op.f('ix_ai_assistant_session_is_active'), table_name='ai_assistant_session')
    op.drop_index(op.f('ix_ai_assistant_session_group_id'), table_name='ai_assistant_session')
    op.drop_index(op.f('ix_ai_assistant_session_chat_id'), table_name='ai_assistant_session')
    op.drop_table('ai_assistant_session')
    op.drop_index(op.f('ix_ai_assistant_message_session_id'), table_name='ai_assistant_message')
    op.drop_index(op.f('ix_ai_assistant_message_message_type'), table_name='ai_assistant_message')
    op.drop_index(op.f('ix_ai_assistant_message_is_deleted'), table_name='ai_assistant_message')
    op.drop_table('ai_assistant_message')
    op.drop_index(op.f('ix_ai_assistant_group_is_deleted'), table_name='ai_assistant_group')
    op.drop_index(op.f('ix_ai_assistant_group_is_active'), table_name='ai_assistant_group')
    op.drop_index(op.f('ix_ai_assistant_group_group_id'), table_name='ai_assistant_group')
    op.drop_table('ai_assistant_group')
    # ### end Alembic commands ###
