"""add ai_role table and group_role association

Revision ID: 11e42496ca4c
Revises: 0e73e2b0dc65
Create Date: 2026-04-12 23:50:20.893969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11e42496ca4c'
down_revision: Union[str, None] = '0e73e2b0dc65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_assistant_role',
    sa.Column('name', sa.String(length=50), nullable=False, comment='角色名称'),
    sa.Column('code', sa.String(length=50), nullable=False, comment='角色编码'),
    sa.Column('description', sa.Text(), nullable=True, comment='角色描述'),
    sa.Column('system_prompt', sa.Text(), nullable=True, comment='系统提示词'),
    sa.Column('avatar', sa.String(length=512), nullable=True, comment='角色头像URL'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('id', sa.String(length=21), nullable=False, comment='主键ID(NanoId)'),
    sa.Column('sort', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='是否删除'),
    sa.Column('sys_create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('sys_update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('sys_creator_id', sa.String(length=21), nullable=True, comment='创建人ID（逻辑外键关联core_user）'),
    sa.Column('sys_modifier_id', sa.String(length=21), nullable=True, comment='修改人ID（逻辑外键关联core_user）'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_assistant_role_code'), 'ai_assistant_role', ['code'], unique=True)
    op.create_index(op.f('ix_ai_assistant_role_is_active'), 'ai_assistant_role', ['is_active'], unique=False)
    op.create_index(op.f('ix_ai_assistant_role_is_deleted'), 'ai_assistant_role', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_ai_assistant_role_name'), 'ai_assistant_role', ['name'], unique=True)
    op.create_table('ai_group_role',
    sa.Column('group_id', sa.String(length=21), nullable=False),
    sa.Column('role_id', sa.String(length=21), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=True, comment='排序'),
    sa.ForeignKeyConstraint(['group_id'], ['ai_assistant_group.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['ai_assistant_role.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id', 'role_id')
    )
    op.alter_column('ai_assistant_group', 'trigger_word',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_comment='触发词')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ai_assistant_group', 'trigger_word',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_comment='触发词')
    op.drop_table('ai_group_role')
    op.drop_index(op.f('ix_ai_assistant_role_name'), table_name='ai_assistant_role')
    op.drop_index(op.f('ix_ai_assistant_role_is_deleted'), table_name='ai_assistant_role')
    op.drop_index(op.f('ix_ai_assistant_role_is_active'), table_name='ai_assistant_role')
    op.drop_index(op.f('ix_ai_assistant_role_code'), table_name='ai_assistant_role')
    op.drop_table('ai_assistant_role')
    # ### end Alembic commands ###
