"""add testcase_id to env_machine_log

Revision ID: 18d727f9b724
Revises: cb76b93485bf
Create Date: 2026-04-08 23:42:38.576814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18d727f9b724'
down_revision: Union[str, None] = 'cb76b93485bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('env_machine_log', sa.Column('testcase_id', sa.String(length=128), nullable=True, comment='用例编号'))
    op.create_index('ix_env_machine_log_testcase_id', 'env_machine_log', ['testcase_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_env_machine_log_testcase_id', table_name='env_machine_log')
    op.drop_column('env_machine_log', 'testcase_id')
    # ### end Alembic commands ###
