"""fix role association tables id column length

Revision ID: 2054c5680962
Revises: 49fd0b7273db
Create Date: 2026-05-31 01:55:30.139978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2054c5680962'
down_revision: Union[str, None] = '49fd0b7273db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('core_role_dept', 'role_id',
               existing_type=sa.VARCHAR(length=21),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('core_role_dept', 'dept_id',
               existing_type=sa.VARCHAR(length=21),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('core_role_menu', 'role_id',
               existing_type=sa.VARCHAR(length=21),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('core_role_menu', 'menu_id',
               existing_type=sa.VARCHAR(length=21),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('core_role_permission', 'role_id',
               existing_type=sa.VARCHAR(length=21),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('core_role_permission', 'permission_id',
               existing_type=sa.VARCHAR(length=21),
               type_=sa.String(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('core_role_permission', 'permission_id',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=21),
               existing_nullable=False)
    op.alter_column('core_role_permission', 'role_id',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=21),
               existing_nullable=False)
    op.alter_column('core_role_menu', 'menu_id',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=21),
               existing_nullable=False)
    op.alter_column('core_role_menu', 'role_id',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=21),
               existing_nullable=False)
    op.alter_column('core_role_dept', 'dept_id',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=21),
               existing_nullable=False)
    op.alter_column('core_role_dept', 'role_id',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=21),
               existing_nullable=False)
    # ### end Alembic commands ###
