"""add execute_host_ip to scheduler_job

Revision ID: 3c0071924a91
Revises: 9d3cec2e2ec1
Create Date: 2026-04-04 00:33:20.455342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c0071924a91'
down_revision: Union[str, None] = '9d3cec2e2ec1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('core_scheduler_job', sa.Column('execute_host_ip', sa.String(length=64), nullable=True, comment='执行主机IP'))
    op.alter_column('core_scheduler_log', 'hostname',
               existing_type=sa.VARCHAR(length=128),
               comment='执行主机IP',
               existing_comment='执行主机',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('core_scheduler_log', 'hostname',
               existing_type=sa.VARCHAR(length=128),
               comment='执行主机',
               existing_comment='执行主机IP',
               existing_nullable=True)
    op.drop_column('core_scheduler_job', 'execute_host_ip')
    # ### end Alembic commands ###
