"""add config_status and scripts fields to env_machine

Revision ID: 4c7e414427f6
Revises: a88d9b9c688b
Create Date: 2026-05-19 01:20:27.977152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c7e414427f6'
down_revision: Union[str, None] = 'a88d9b9c688b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('env_machine', sa.Column('config_status', sa.String(length=20), nullable=True, comment='配置状态: updating/null'))
    op.add_column('env_machine', sa.Column('scripts', sa.JSON(), nullable=True, comment='脚本版本字典'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('env_machine', 'scripts')
    op.drop_column('env_machine', 'config_status')
    # ### end Alembic commands ###
