"""add asset_number to env_machine

Revision ID: 4d672ac66c71
Revises: 6503c83516d3
Create Date: 2026-03-25 20:19:45.666286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d672ac66c71'
down_revision: Union[str, None] = '6503c83516d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('env_machine', sa.Column('asset_number', sa.String(length=32), nullable=True, comment='资产编号'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('env_machine', 'asset_number')
    # ### end Alembic commands ###
