"""add test_report tables

Revision ID: 58e19bd042d2
Revises: fd586a9cc5ef
Create Date: 2026-03-30 00:50:13.511715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '58e19bd042d2'
down_revision: Union[str, None] = 'fd586a9cc5ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_report_detail',
    sa.Column('task_id', sa.String(length=21), nullable=False, comment='任务执行ID'),
    sa.Column('task_name', sa.String(length=100), nullable=False, comment='任务名称'),
    sa.Column('total_cases', sa.Integer(), nullable=False, comment='用例总数'),
    sa.Column('case_name', sa.String(length=200), nullable=False, comment='用例标题'),
    sa.Column('case_fail_step', sa.String(length=100), nullable=False, comment='失败步骤名称'),
    sa.Column('case_fail_log', sa.Text(), nullable=False, comment='失败日志'),
    sa.Column('case_round', sa.Integer(), nullable=False, comment='失败轮次'),
    sa.Column('log_url', sa.String(length=500), nullable=True, comment='完整日志地址'),
    sa.Column('fail_time', sa.DateTime(), nullable=True, comment='失败时间'),
    sa.Column('id', sa.String(length=21), nullable=False, comment='主键ID(NanoId)'),
    sa.Column('sort', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='是否删除'),
    sa.Column('sys_create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('sys_update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('sys_creator_id', sa.String(length=21), nullable=True, comment='创建人ID（逻辑外键关联core_user）'),
    sa.Column('sys_modifier_id', sa.String(length=21), nullable=True, comment='修改人ID（逻辑外键关联core_user）'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_task_case_round', 'test_report_detail', ['task_id', 'case_name', 'case_round'], unique=False)
    op.create_index(op.f('ix_test_report_detail_is_deleted'), 'test_report_detail', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_test_report_detail_task_id'), 'test_report_detail', ['task_id'], unique=False)
    op.create_table('test_report_summary',
    sa.Column('task_id', sa.String(length=21), nullable=False, comment='任务执行ID'),
    sa.Column('task_name', sa.String(length=100), nullable=False, comment='任务名称'),
    sa.Column('task_base_name', sa.String(length=100), nullable=True, comment='任务基础名称'),
    sa.Column('total_cases', sa.Integer(), nullable=False, comment='用例总数'),
    sa.Column('fail_total', sa.Integer(), nullable=False, comment='失败总数'),
    sa.Column('pass_rate', sa.String(length=10), nullable=False, comment='通过率'),
    sa.Column('compare_change', sa.Integer(), nullable=True, comment='同比变化'),
    sa.Column('last_fail_total', sa.Integer(), nullable=True, comment='上次执行失败数'),
    sa.Column('round_stats', sa.JSON(), nullable=True, comment='轮次统计'),
    sa.Column('fail_always', sa.Integer(), nullable=True, comment='每轮都失败数'),
    sa.Column('fail_unstable', sa.Integer(), nullable=True, comment='不稳定用例数'),
    sa.Column('step_distribution', sa.JSON(), nullable=True, comment='失败步骤分布'),
    sa.Column('ai_analysis', sa.Text(), nullable=True, comment='AI分析结论'),
    sa.Column('analysis_status', sa.String(length=20), nullable=True, comment='分析状态'),
    sa.Column('execute_time', sa.DateTime(), nullable=True, comment='执行时间'),
    sa.Column('last_report_time', sa.DateTime(), nullable=True, comment='最后上报时间'),
    sa.Column('id', sa.String(length=21), nullable=False, comment='主键ID(NanoId)'),
    sa.Column('sort', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='是否删除'),
    sa.Column('sys_create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('sys_update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('sys_creator_id', sa.String(length=21), nullable=True, comment='创建人ID（逻辑外键关联core_user）'),
    sa.Column('sys_modifier_id', sa.String(length=21), nullable=True, comment='修改人ID（逻辑外键关联core_user）'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id')
    )
    op.create_index('idx_last_report_time', 'test_report_summary', ['last_report_time'], unique=False)
    op.create_index('idx_task_base_name', 'test_report_summary', ['task_base_name'], unique=False)
    op.create_index(op.f('ix_test_report_summary_execute_time'), 'test_report_summary', ['execute_time'], unique=False)
    op.create_index(op.f('ix_test_report_summary_is_deleted'), 'test_report_summary', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_test_report_summary_last_report_time'), 'test_report_summary', ['last_report_time'], unique=False)
    op.create_index(op.f('ix_test_report_summary_task_base_name'), 'test_report_summary', ['task_base_name'], unique=False)
    op.create_index(op.f('ix_test_report_summary_task_name'), 'test_report_summary', ['task_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_report_summary_task_name'), table_name='test_report_summary')
    op.drop_index(op.f('ix_test_report_summary_task_base_name'), table_name='test_report_summary')
    op.drop_index(op.f('ix_test_report_summary_last_report_time'), table_name='test_report_summary')
    op.drop_index(op.f('ix_test_report_summary_is_deleted'), table_name='test_report_summary')
    op.drop_index(op.f('ix_test_report_summary_execute_time'), table_name='test_report_summary')
    op.drop_index('idx_task_base_name', table_name='test_report_summary')
    op.drop_index('idx_last_report_time', table_name='test_report_summary')
    op.drop_table('test_report_summary')
    op.drop_index(op.f('ix_test_report_detail_task_id'), table_name='test_report_detail')
    op.drop_index(op.f('ix_test_report_detail_is_deleted'), table_name='test_report_detail')
    op.drop_index('idx_task_case_round', table_name='test_report_detail')
    op.drop_table('test_report_detail')
    # ### end Alembic commands ###
