"""add config_template table and config_version field

Revision ID: 5d714220f329
Revises: a1b2c3d4e5f7
Create Date: 2026-04-15 22:46:25.608728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d714220f329'
down_revision: Union[str, None] = 'a1b2c3d4e5f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config_template',
    sa.Column('name', sa.String(length=64), nullable=False, comment='模板名称'),
    sa.Column('namespace', sa.String(length=64), nullable=True, comment='适用命名空间'),
    sa.Column('note', sa.Text(), nullable=True, comment='备注说明'),
    sa.Column('config_content', sa.Text(), nullable=False, comment='YAML配置内容'),
    sa.Column('version', sa.String(length=20), nullable=False, comment='版本号YYYYMMDD-HHMMSS'),
    sa.Column('id', sa.String(length=21), nullable=False, comment='主键ID(NanoId)'),
    sa.Column('sort', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='是否删除'),
    sa.Column('sys_create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('sys_update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('sys_creator_id', sa.String(length=21), nullable=True, comment='创建人ID（逻辑外键关联core_user）'),
    sa.Column('sys_modifier_id', sa.String(length=21), nullable=True, comment='修改人ID（逻辑外键关联core_user）'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_config_template_is_deleted'), 'config_template', ['is_deleted'], unique=False)
    op.create_index('ix_config_template_namespace', 'config_template', ['namespace'], unique=False)
    op.add_column('env_machine', sa.Column('config_version', sa.String(length=20), nullable=True, comment='配置版本'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('env_machine', 'config_version')
    op.drop_index('ix_config_template_namespace', table_name='config_template')
    op.drop_index(op.f('ix_config_template_is_deleted'), table_name='config_template')
    op.drop_table('config_template')
    # ### end Alembic commands ###
