"""add feature_analysis table

Revision ID: 5dcf7cb79e39
Revises: a79453452d83
Create Date: 2026-03-22 22:18:54.827893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5dcf7cb79e39'
down_revision: Union[str, None] = 'a79453452d83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feature_analysis',
    sa.Column('feature_id_father', sa.String(length=64), nullable=True, comment='父工作项ID'),
    sa.Column('feature_id', sa.String(length=64), nullable=True, comment='需求ID'),
    sa.Column('feature_desc', sa.String(length=255), nullable=True, comment='需求标题'),
    sa.Column('feature_services', sa.String(length=64), nullable=True, comment='开发归属'),
    sa.Column('feature_task_id', sa.String(length=64), nullable=True, comment='需求task id'),
    sa.Column('feature_task_service', sa.String(length=64), nullable=True, comment='测试归属'),
    sa.Column('feature_owner', sa.String(length=64), nullable=True, comment='测试责任人'),
    sa.Column('feature_dev_owner', sa.String(length=64), nullable=True, comment='开发责任人'),
    sa.Column('feature_safe_test', sa.String(length=64), nullable=True, comment='涉及安全'),
    sa.Column('feature_code', sa.String(length=64), nullable=True, comment='代码量'),
    sa.Column('feature_test_count', sa.String(length=64), nullable=True, comment='需求转测次数'),
    sa.Column('feature_test_expect_time', sa.String(length=64), nullable=True, comment='预计转测时间'),
    sa.Column('feature_test_start_time', sa.String(length=64), nullable=True, comment='实际转测时间'),
    sa.Column('feature_test_end_time', sa.String(length=64), nullable=True, comment='完成测试时间'),
    sa.Column('feature_judge', sa.Text(), nullable=True, comment='特性质量评价'),
    sa.Column('feature_bug_total', sa.String(length=64), nullable=True, comment='问题单数量'),
    sa.Column('feature_bug_serious', sa.String(length=64), nullable=True, comment='严重以上数量'),
    sa.Column('feature_bug_general', sa.String(length=64), nullable=True, comment='一般数量'),
    sa.Column('feature_bug_prompt', sa.String(length=64), nullable=True, comment='提示数量'),
    sa.Column('feature_bug_detail', sa.String(length=255), nullable=True, comment='引入问题单号'),
    sa.Column('feature_progress', sa.Text(), nullable=True, comment='测试进展'),
    sa.Column('feature_risk', sa.Text(), nullable=True, comment='风险与关键问题'),
    sa.Column('feature_version', sa.String(length=64), nullable=True, comment='需求归属版本'),
    sa.Column('sync_time', sa.String(length=64), nullable=True, comment='数据同步时间'),
    sa.Column('create_by', sa.String(length=64), nullable=True, comment='创建者'),
    sa.Column('create_time', sa.String(length=64), nullable=True, comment='创建时间'),
    sa.Column('modify_time', sa.String(length=64), nullable=True, comment='修改时间'),
    sa.Column('id', sa.String(length=21), nullable=False, comment='主键ID(NanoId)'),
    sa.Column('sort', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='是否删除'),
    sa.Column('sys_create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('sys_update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('sys_creator_id', sa.String(length=21), nullable=True, comment='创建人ID（逻辑外键关联core_user）'),
    sa.Column('sys_modifier_id', sa.String(length=21), nullable=True, comment='修改人ID（逻辑外键关联core_user）'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_feature_deleted', 'feature_analysis', ['is_deleted'], unique=False)
    op.create_index('idx_feature_version', 'feature_analysis', ['feature_version'], unique=False)
    op.create_index(op.f('ix_feature_analysis_is_deleted'), 'feature_analysis', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feature_analysis_is_deleted'), table_name='feature_analysis')
    op.drop_index('idx_feature_version', table_name='feature_analysis')
    op.drop_index('idx_feature_deleted', table_name='feature_analysis')
    op.drop_table('feature_analysis')
    # ### end Alembic commands ###
