"""add env_machine table

Revision ID: 6503c83516d3
Revises: 9c73a09f95db
Create Date: 2026-03-25 01:06:02.164035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6503c83516d3'
down_revision: Union[str, None] = '9c73a09f95db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('env_machine',
    sa.Column('namespace', sa.String(length=64), nullable=False, comment='机器分类'),
    sa.Column('ip', sa.String(length=45), nullable=False, comment='机器 IP'),
    sa.Column('port', sa.String(length=10), nullable=False, comment='机器端口'),
    sa.Column('mark', sa.String(length=255), nullable=True, comment='机器标签'),
    sa.Column('device_type', sa.String(length=20), nullable=False, comment='机器类型'),
    sa.Column('device_sn', sa.String(length=64), nullable=True, comment='设备 SN'),
    sa.Column('available', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态'),
    sa.Column('note', sa.Text(), nullable=True, comment='备注'),
    sa.Column('sync_time', sa.DateTime(), nullable=False, comment='同步时间'),
    sa.Column('extra_message', sa.JSON(), nullable=True, comment='扩展信息'),
    sa.Column('version', sa.String(length=32), nullable=True, comment='机器版本'),
    sa.Column('last_keepusing_time', sa.DateTime(), nullable=True, comment='最后保持使用时间'),
    sa.Column('id', sa.String(length=21), nullable=False, comment='主键ID(NanoId)'),
    sa.Column('sort', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='是否删除'),
    sa.Column('sys_create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('sys_update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('sys_creator_id', sa.String(length=21), nullable=True, comment='创建人ID（逻辑外键关联core_user）'),
    sa.Column('sys_modifier_id', sa.String(length=21), nullable=True, comment='修改人ID（逻辑外键关联core_user）'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('namespace', 'ip', 'device_type', 'device_sn', name='uq_env_machine_namespace_ip_device')
    )
    op.create_index(op.f('ix_env_machine_is_deleted'), 'env_machine', ['is_deleted'], unique=False)
    op.create_index('ix_env_machine_status', 'env_machine', ['status'], unique=False)
    op.create_index('ix_env_machine_sync_time', 'env_machine', ['sync_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_env_machine_sync_time', table_name='env_machine')
    op.drop_index('ix_env_machine_status', table_name='env_machine')
    op.drop_index(op.f('ix_env_machine_is_deleted'), table_name='env_machine')
    op.drop_table('env_machine')
    # ### end Alembic commands ###
