"""add testcase_id to env_machine_log

Revision ID: 8c65b4bf9f40
Revises: 18d727f9b724
Create Date: 2026-04-08 23:44:19.763492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c65b4bf9f40'
down_revision: Union[str, None] = '18d727f9b724'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
