"""change compare_tag time to integer

Revision ID: 95c464f48885
Revises: e5f6g7h8i9j0
Create Date: 2026-05-17 17:41:05.926005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '95c464f48885'
down_revision: Union[str, None] = 'e5f6g7h8i9j0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('config_template', 'type',
               existing_type=sa.VARCHAR(length=20),
               comment='模板类型',
               existing_comment='模板类型: config/script',
               existing_nullable=False,
               existing_server_default=sa.text("'config'::character varying"))
    op.alter_column('config_template', 'config_content',
               existing_type=sa.TEXT(),
               comment='配置内容',
               existing_comment='YAML配置内容',
               existing_nullable=False)
    op.alter_column('config_template', 'id',
               existing_type=sa.VARCHAR(length=21),
               type_=sa.String(length=50),
               existing_comment='主键ID(NanoId)',
               existing_nullable=False)
    op.alter_column('config_template', 'sys_creator_id',
               existing_type=sa.VARCHAR(length=21),
               type_=sa.String(length=50),
               existing_comment='创建人ID（逻辑外键关联core_user）',
               existing_nullable=True)
    op.alter_column('config_template', 'sys_modifier_id',
               existing_type=sa.VARCHAR(length=21),
               type_=sa.String(length=50),
               existing_comment='修改人ID（逻辑外键关联core_user）',
               existing_nullable=True)
    op.create_index('ix_config_template_type', 'config_template', ['type'], unique=False)
    op.alter_column('core_dept', 'id',
               existing_type=sa.VARCHAR(length=21),
               type_=sa.String(length=50),
               existing_comment='主键ID(NanoId)',
               existing_nullable=False)
    op.alter_column('core_dept', 'sys_creator_id',
               existing_type=sa.VARCHAR(length=21),
               type_=sa.String(length=50),
               existing_comment='创建人ID（逻辑外键关联core_user）',
               existing_nullable=True)
    op.alter_column('core_dept', 'sys_modifier_id',
               existing_type=sa.VARCHAR(length=21),
               type_=sa.String(length=50),
               existing_comment='修改人ID（逻辑外键关联core_user）',
               existing_nullable=True)
    op.alter_column('core_login_log', 'id',
               existing_type=sa.VARCHAR(length=21),
               type_=sa.String(length=50),
               existing_comment='主键ID(NanoId)',
               existing_nullable=False)
    op.alter_column('core_login_log', 'sys_creator_id',
               existing_type=sa.VARCHAR(length=21),
               type_=sa.String(length=50),
               existing_comment='创建人ID（逻辑外键关联core_user）',
               existing_nullable=True)
    op.alter_column('core_login_log', 'sys_modifier_id',
               existing_type=sa.VARCHAR(length=21),
               type_=sa.String(length=50),
               existing_comment='修改人ID（逻辑外键关联core_user）',
               existing_nullable=True)
    op.alter_column('core_menu', 'sys_creator_id',
               existing_type=sa.VARCHAR(length=21),
               type_=sa.String(length=50),
               existing_comment='创建人ID（逻辑外键关联core_user）',
               existing_nullable=True)
    op.alter_column('core_menu', 'sys_modifier_id',
               existing_type=sa.VARCHAR(length=21),
               type_=sa.String(length=50),
               existing_comment='修改人ID（逻辑外键关联core_user）',
               existing_nullable=True)
    op.alter_column('core_permission', 'id',
               existing_type=sa.VARCHAR(length=21),
               type_=sa.String(length=50),
               existing_comment='主键ID(NanoId)',
               existing_nullable=False)
    op.alter_column('core_permission', 'sys_creator_id',
               existing_type=sa.VARCHAR(length=21),
               type_=sa.String(length=50),
               existing_comment='创建人ID（逻辑外键关联core_user）',
               existing_nullable=True)
    op.alter_column('core_permission', 'sys_modifier_id',
               existing_type=sa.VARCHAR(length=21),
               type_=sa.String(length=50),
               existing_comment='修改人ID（逻辑外键关联core_user）',
               existing_nullable=True)
    op.alter_column('core_role', 'sys_creator_id',
               existing_type=sa.VARCHAR(length=21),
               type_=sa.String(length=50),
               existing_comment='创建人ID（逻辑外键关联core_user）',
               existing_nullable=True)
    op.alter_column('core_role', 'sys_modifier_id',
               existing_type=sa.VARCHAR(length=21),
               type_=sa.String(length=50),
               existing_comment='修改人ID（逻辑外键关联core_user）',
               existing_nullable=True)
    op.alter_column('core_role_menu', 'role_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=21),
               existing_nullable=False)
    op.alter_column('core_role_menu', 'menu_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=21),
               existing_nullable=False)
    op.alter_column('core_scheduler_job', 'id',
               existing_type=sa.VARCHAR(length=21),
               type_=sa.String(length=50),
               existing_comment='主键ID(NanoId)',
               existing_nullable=False)
    op.alter_column('core_scheduler_job', 'sys_creator_id',
               existing_type=sa.VARCHAR(length=21),
               type_=sa.String(length=50),
               existing_comment='创建人ID（逻辑外键关联core_user）',
               existing_nullable=True)
    op.alter_column('core_scheduler_job', 'sys_modifier_id',
               existing_type=sa.VARCHAR(length=21),
               type_=sa.String(length=50),
               existing_comment='修改人ID（逻辑外键关联core_user）',
               existing_nullable=True)
    op.alter_column('core_scheduler_log', 'id',
               existing_type=sa.VARCHAR(length=21),
               type_=sa.String(length=50),
               existing_comment='主键ID(NanoId)',
               existing_nullable=False)
    op.alter_column('core_scheduler_log', 'sys_creator_id',
               existing_type=sa.VARCHAR(length=21),
               type_=sa.String(length=50),
               existing_comment='创建人ID（逻辑外键关联core_user）',
               existing_nullable=True)
    op.alter_column('core_scheduler_log', 'sys_modifier_id',
               existing_type=sa.VARCHAR(length=21),
               type_=sa.String(length=50),
               existing_comment='修改人ID（逻辑外键关联core_user）',
               existing_nullable=True)
    op.alter_column('core_user', 'id',
               existing_type=sa.VARCHAR(length=21),
               type_=sa.String(length=50),
               existing_comment='主键ID(NanoId)',
               existing_nullable=False)
    op.alter_column('core_user', 'sys_creator_id',
               existing_type=sa.VARCHAR(length=21),
               type_=sa.String(length=50),
               existing_comment='创建人ID（逻辑外键关联core_user）',
               existing_nullable=True)
    op.alter_column('core_user', 'sys_modifier_id',
               existing_type=sa.VARCHAR(length=21),
               type_=sa.String(length=50),
               existing_comment='修改人ID（逻辑外键关联core_user）',
               existing_nullable=True)
    op.alter_column('env_machine', 'id',
               existing_type=sa.VARCHAR(length=21),
               type_=sa.String(length=50),
               existing_comment='主键ID(NanoId)',
               existing_nullable=False)
    op.alter_column('env_machine', 'sys_creator_id',
               existing_type=sa.VARCHAR(length=21),
               type_=sa.String(length=50),
               existing_comment='创建人ID（逻辑外键关联core_user）',
               existing_nullable=True)
    op.alter_column('env_machine', 'sys_modifier_id',
               existing_type=sa.VARCHAR(length=21),
               type_=sa.String(length=50),
               existing_comment='修改人ID（逻辑外键关联core_user）',
               existing_nullable=True)
    op.alter_column('env_machine_log', 'id',
               existing_type=sa.VARCHAR(length=21),
               type_=sa.String(length=50),
               existing_comment='主键ID(NanoId)',
               existing_nullable=False)
    op.alter_column('env_machine_log', 'sys_creator_id',
               existing_type=sa.VARCHAR(length=21),
               type_=sa.String(length=50),
               existing_comment='创建人ID（逻辑外键关联core_user）',
               existing_nullable=True)
    op.alter_column('env_machine_log', 'sys_modifier_id',
               existing_type=sa.VARCHAR(length=21),
               type_=sa.String(length=50),
               existing_comment='修改人ID（逻辑外键关联core_user）',
               existing_nullable=True)
    op.alter_column('feature_analysis', 'id',
               existing_type=sa.VARCHAR(length=21),
               type_=sa.String(length=50),
               existing_comment='主键ID(NanoId)',
               existing_nullable=False)
    op.alter_column('feature_analysis', 'sys_creator_id',
               existing_type=sa.VARCHAR(length=21),
               type_=sa.String(length=50),
               existing_comment='创建人ID（逻辑外键关联core_user）',
               existing_nullable=True)
    op.alter_column('feature_analysis', 'sys_modifier_id',
               existing_type=sa.VARCHAR(length=21),
               type_=sa.String(length=50),
               existing_comment='修改人ID（逻辑外键关联core_user）',
               existing_nullable=True)
    op.alter_column('issues_analysis', 'id',
               existing_type=sa.VARCHAR(length=21),
               type_=sa.String(length=50),
               existing_comment='主键ID(NanoId)',
               existing_nullable=False)
    op.alter_column('issues_analysis', 'sys_creator_id',
               existing_type=sa.VARCHAR(length=21),
               type_=sa.String(length=50),
               existing_comment='创建人ID（逻辑外键关联core_user）',
               existing_nullable=True)
    op.alter_column('issues_analysis', 'sys_modifier_id',
               existing_type=sa.VARCHAR(length=21),
               type_=sa.String(length=50),
               existing_comment='修改人ID（逻辑外键关联core_user）',
               existing_nullable=True)
    op.alter_column('performance_collect', 'device_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=21),
               comment='设备ID',
               existing_nullable=False)
    op.alter_column('performance_collect', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment='采集名称',
               existing_nullable=True)
    op.alter_column('performance_collect', 'start_time',
               existing_type=postgresql.TIMESTAMP(),
               comment='开始时间',
               existing_nullable=False)
    op.alter_column('performance_collect', 'end_time',
               existing_type=postgresql.TIMESTAMP(),
               comment='结束时间',
               existing_nullable=True)
    op.alter_column('performance_collect', 'interval',
               existing_type=sa.INTEGER(),
               comment='采集频率（秒）',
               existing_nullable=False,
               existing_server_default=sa.text('5'))
    op.alter_column('performance_collect', 'target_processes',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='目标进程配置',
               existing_nullable=True)
    op.alter_column('performance_collect', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='状态：running/stopped/error',
               existing_nullable=False,
               existing_server_default=sa.text("'running'::character varying"))
    op.alter_column('performance_collect', 'is_protected',
               existing_type=sa.BOOLEAN(),
               comment='保护标记',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('performance_collect', 'id',
               existing_type=sa.VARCHAR(length=50),
               comment='主键ID(NanoId)',
               existing_nullable=False)
    op.alter_column('performance_collect', 'sort',
               existing_type=sa.INTEGER(),
               comment='排序',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('performance_collect', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               comment='是否删除',
               existing_nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('performance_collect', 'sys_create_datetime',
               existing_type=postgresql.TIMESTAMP(),
               comment='创建时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('performance_collect', 'sys_update_datetime',
               existing_type=postgresql.TIMESTAMP(),
               comment='更新时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('performance_collect', 'sys_creator_id',
               existing_type=sa.VARCHAR(length=50),
               comment='创建人ID（逻辑外键关联core_user）',
               existing_nullable=True)
    op.alter_column('performance_collect', 'sys_modifier_id',
               existing_type=sa.VARCHAR(length=50),
               comment='修改人ID（逻辑外键关联core_user）',
               existing_nullable=True)
    # 删除旧的 compare_tag 表（如果存在），重建为新结构（使用相对秒数）
    op.execute("DROP TABLE IF EXISTS performance_compare_tag CASCADE")
    op.create_table(
        'performance_compare_tag',
        sa.Column('id', sa.String(length=50), nullable=False, primary_key=True, comment='主键ID(NanoId)'),
        sa.Column('sort', sa.Integer(), nullable=True, server_default='0', comment='排序'),
        sa.Column('is_deleted', sa.Boolean(), nullable=True, server_default='false', comment='是否删除'),
        sa.Column('sys_create_datetime', postgresql.TIMESTAMP(), nullable=True, server_default='CURRENT_TIMESTAMP', comment='创建时间'),
        sa.Column('sys_update_datetime', postgresql.TIMESTAMP(), nullable=True, server_default='CURRENT_TIMESTAMP', comment='更新时间'),
        sa.Column('sys_creator_id', sa.String(length=50), nullable=True, comment='创建人ID（逻辑外键关联core_user）'),
        sa.Column('sys_modifier_id', sa.String(length=50), nullable=True, comment='修改人ID（逻辑外键关联core_user）'),
        sa.Column('name', sa.String(length=100), nullable=False, comment='标签名称'),
        sa.Column('type', sa.String(length=20), nullable=False, server_default='peak', comment='类型: peak(冲高) / stable(稳态)'),
        sa.Column('start_time', sa.Integer(), nullable=False, comment='开始时间（相对秒数）'),
        sa.Column('end_time', sa.Integer(), nullable=False, comment='结束时间（相对秒数）'),
        sa.Column('note', sa.Text(), nullable=True, comment='备注'),
    )
    op.alter_column('performance_data', 'collect_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=21),
               comment='采集记录ID',
               existing_nullable=False)
    op.alter_column('performance_data', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               comment='实际时间',
               existing_nullable=False)
    op.alter_column('performance_data', 'relative_time',
               existing_type=sa.INTEGER(),
               comment='相对时间（秒）',
               existing_nullable=False)
    op.alter_column('performance_data', 'cpu_usage',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='CPU使用率 %',
               existing_nullable=True)
    op.alter_column('performance_data', 'gpu_usage',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='GPU使用率 %',
               existing_nullable=True)
    op.alter_column('performance_data', 'commit_memory',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='提交内存 GB',
               existing_nullable=True)
    op.alter_column('performance_data', 'memory_usage',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='内存使用 GB',
               existing_nullable=True)
    op.alter_column('performance_data', 'process_handles',
               existing_type=sa.INTEGER(),
               comment='进程句柄数',
               existing_nullable=True)
    op.alter_column('performance_data', 'target_processes',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='目标进程数据',
               existing_nullable=True)
    op.alter_column('performance_data', 'top10_cpu',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='CPU TOP10',
               existing_nullable=True)
    op.alter_column('performance_data', 'top10_gpu',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='GPU TOP10',
               existing_nullable=True)
    op.alter_column('performance_data', 'id',
               existing_type=sa.VARCHAR(length=50),
               comment='主键ID(NanoId)',
               existing_nullable=False)
    op.alter_column('performance_data', 'sort',
               existing_type=sa.INTEGER(),
               comment='排序',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('performance_data', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               comment='是否删除',
               existing_nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('performance_data', 'sys_create_datetime',
               existing_type=postgresql.TIMESTAMP(),
               comment='创建时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('performance_data', 'sys_update_datetime',
               existing_type=postgresql.TIMESTAMP(),
               comment='更新时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('performance_data', 'sys_creator_id',
               existing_type=sa.VARCHAR(length=50),
               comment='创建人ID（逻辑外键关联core_user）',
               existing_nullable=True)
    op.alter_column('performance_data', 'sys_modifier_id',
               existing_type=sa.VARCHAR(length=50),
               comment='修改人ID（逻辑外键关联core_user）',
               existing_nullable=True)
    op.alter_column('performance_marker', 'sys_creator_id',
               existing_type=sa.VARCHAR(length=50),
               comment='创建人ID（逻辑外键关联core_user）',
               existing_comment='创建人ID',
               existing_nullable=True)
    op.alter_column('performance_marker', 'sys_modifier_id',
               existing_type=sa.VARCHAR(length=50),
               comment='修改人ID（逻辑外键关联core_user）',
               existing_comment='修改人ID',
               existing_nullable=True)
    op.alter_column('performance_metric_mapping', 'sys_creator_id',
               existing_type=sa.VARCHAR(length=50),
               comment='创建人ID（逻辑外键关联core_user）',
               existing_comment='创建人ID',
               existing_nullable=True)
    op.alter_column('performance_metric_mapping', 'sys_modifier_id',
               existing_type=sa.VARCHAR(length=50),
               comment='修改人ID（逻辑外键关联core_user）',
               existing_comment='修改人ID',
               existing_nullable=True)
    op.alter_column('performance_tag', 'collect_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=21),
               comment='采集记录ID',
               existing_nullable=False)
    op.alter_column('performance_tag', 'name',
               existing_type=sa.VARCHAR(length=50),
               comment='标签名称',
               existing_nullable=False)
    op.alter_column('performance_tag', 'start_relative_time',
               existing_type=sa.INTEGER(),
               comment='起始相对时间（秒）',
               existing_nullable=False)
    op.alter_column('performance_tag', 'duration',
               existing_type=sa.INTEGER(),
               comment='时间长度（秒）',
               existing_nullable=False)
    op.alter_column('performance_tag', 'type',
               existing_type=sa.VARCHAR(length=20),
               comment='类型：peak/mean',
               existing_nullable=False,
               existing_server_default=sa.text("'peak'::character varying"))
    op.alter_column('performance_tag', 'id',
               existing_type=sa.VARCHAR(length=50),
               comment='主键ID(NanoId)',
               existing_nullable=False)
    op.alter_column('performance_tag', 'sort',
               existing_type=sa.INTEGER(),
               comment='排序',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('performance_tag', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               comment='是否删除',
               existing_nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('performance_tag', 'sys_create_datetime',
               existing_type=postgresql.TIMESTAMP(),
               comment='创建时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('performance_tag', 'sys_update_datetime',
               existing_type=postgresql.TIMESTAMP(),
               comment='更新时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('performance_tag', 'sys_creator_id',
               existing_type=sa.VARCHAR(length=50),
               comment='创建人ID（逻辑外键关联core_user）',
               existing_nullable=True)
    op.alter_column('performance_tag', 'sys_modifier_id',
               existing_type=sa.VARCHAR(length=50),
               comment='修改人ID（逻辑外键关联core_user）',
               existing_nullable=True)
    op.alter_column('performance_version', 'device_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=21),
               comment='设备ID',
               existing_nullable=False)
    op.alter_column('performance_version', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment='版本名称',
               existing_nullable=False)
    op.alter_column('performance_version', 'collect_ids',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='包含的采集记录ID列表',
               existing_nullable=False)
    op.alter_column('performance_version', 'time_ranges',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='时间范围映射',
               existing_comment='时间范围映射: {collect_id: {start, end}}',
               existing_nullable=True)
    op.alter_column('performance_version', 'is_protected',
               existing_type=sa.BOOLEAN(),
               comment='保护标记',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('performance_version', 'id',
               existing_type=sa.VARCHAR(length=50),
               comment='主键ID(NanoId)',
               existing_nullable=False)
    op.alter_column('performance_version', 'sort',
               existing_type=sa.INTEGER(),
               comment='排序',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('performance_version', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               comment='是否删除',
               existing_nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('performance_version', 'sys_create_datetime',
               existing_type=postgresql.TIMESTAMP(),
               comment='创建时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('performance_version', 'sys_update_datetime',
               existing_type=postgresql.TIMESTAMP(),
               comment='更新时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('performance_version', 'sys_creator_id',
               existing_type=sa.VARCHAR(length=50),
               comment='创建人ID（逻辑外键关联core_user）',
               existing_nullable=True)
    op.alter_column('performance_version', 'sys_modifier_id',
               existing_type=sa.VARCHAR(length=50),
               comment='修改人ID（逻辑外键关联core_user）',
               existing_nullable=True)
    op.alter_column('test_report_detail', 'testcase_block_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=200),
               existing_comment='用例块ID',
               existing_nullable=False)
    op.alter_column('test_report_detail', 'id',
               existing_type=sa.VARCHAR(length=21),
               type_=sa.String(length=50),
               existing_comment='主键ID(NanoId)',
               existing_nullable=False)
    op.alter_column('test_report_detail', 'sys_creator_id',
               existing_type=sa.VARCHAR(length=21),
               type_=sa.String(length=50),
               existing_comment='创建人ID（逻辑外键关联core_user）',
               existing_nullable=True)
    op.alter_column('test_report_detail', 'sys_modifier_id',
               existing_type=sa.VARCHAR(length=21),
               type_=sa.String(length=50),
               existing_comment='修改人ID（逻辑外键关联core_user）',
               existing_nullable=True)
    op.alter_column('test_report_summary', 'id',
               existing_type=sa.VARCHAR(length=21),
               type_=sa.String(length=50),
               existing_comment='主键ID(NanoId)',
               existing_nullable=False)
    op.alter_column('test_report_summary', 'sys_creator_id',
               existing_type=sa.VARCHAR(length=21),
               type_=sa.String(length=50),
               existing_comment='创建人ID（逻辑外键关联core_user）',
               existing_nullable=True)
    op.alter_column('test_report_summary', 'sys_modifier_id',
               existing_type=sa.VARCHAR(length=21),
               type_=sa.String(length=50),
               existing_comment='修改人ID（逻辑外键关联core_user）',
               existing_nullable=True)
    op.alter_column('test_report_upload_log', 'testcase_block_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=200),
               existing_comment='用例块ID',
               existing_nullable=False)
    op.alter_column('test_report_upload_log', 'id',
               existing_type=sa.VARCHAR(length=21),
               type_=sa.String(length=50),
               existing_comment='主键ID(NanoId)',
               existing_nullable=False)
    op.alter_column('test_report_upload_log', 'sys_creator_id',
               existing_type=sa.VARCHAR(length=21),
               type_=sa.String(length=50),
               existing_comment='创建人ID（逻辑外键关联core_user）',
               existing_nullable=True)
    op.alter_column('test_report_upload_log', 'sys_modifier_id',
               existing_type=sa.VARCHAR(length=21),
               type_=sa.String(length=50),
               existing_comment='修改人ID（逻辑外键关联core_user）',
               existing_nullable=True)
    op.alter_column('worker_upgrade_config', 'id',
               existing_type=sa.VARCHAR(length=21),
               type_=sa.String(length=50),
               existing_comment='主键ID(NanoId)',
               existing_nullable=False)
    op.alter_column('worker_upgrade_config', 'sys_creator_id',
               existing_type=sa.VARCHAR(length=21),
               type_=sa.String(length=50),
               existing_comment='创建人ID（逻辑外键关联core_user）',
               existing_nullable=True)
    op.alter_column('worker_upgrade_config', 'sys_modifier_id',
               existing_type=sa.VARCHAR(length=21),
               type_=sa.String(length=50),
               existing_comment='修改人ID（逻辑外键关联core_user）',
               existing_nullable=True)
    op.alter_column('worker_upgrade_queue', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='状态: waiting/processing/completed/failed',
               existing_comment='状态: waiting/completed/failed',
               existing_nullable=False)
    op.alter_column('worker_upgrade_queue', 'id',
               existing_type=sa.VARCHAR(length=21),
               type_=sa.String(length=50),
               existing_comment='主键ID(NanoId)',
               existing_nullable=False)
    op.alter_column('worker_upgrade_queue', 'sys_creator_id',
               existing_type=sa.VARCHAR(length=21),
               type_=sa.String(length=50),
               existing_comment='创建人ID（逻辑外键关联core_user）',
               existing_nullable=True)
    op.alter_column('worker_upgrade_queue', 'sys_modifier_id',
               existing_type=sa.VARCHAR(length=21),
               type_=sa.String(length=50),
               existing_comment='修改人ID（逻辑外键关联core_user）',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('worker_upgrade_queue', 'sys_modifier_id',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=21),
               existing_comment='修改人ID（逻辑外键关联core_user）',
               existing_nullable=True)
    op.alter_column('worker_upgrade_queue', 'sys_creator_id',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=21),
               existing_comment='创建人ID（逻辑外键关联core_user）',
               existing_nullable=True)
    op.alter_column('worker_upgrade_queue', 'id',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=21),
               existing_comment='主键ID(NanoId)',
               existing_nullable=False)
    op.alter_column('worker_upgrade_queue', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='状态: waiting/completed/failed',
               existing_comment='状态: waiting/processing/completed/failed',
               existing_nullable=False)
    op.alter_column('worker_upgrade_config', 'sys_modifier_id',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=21),
               existing_comment='修改人ID（逻辑外键关联core_user）',
               existing_nullable=True)
    op.alter_column('worker_upgrade_config', 'sys_creator_id',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=21),
               existing_comment='创建人ID（逻辑外键关联core_user）',
               existing_nullable=True)
    op.alter_column('worker_upgrade_config', 'id',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=21),
               existing_comment='主键ID(NanoId)',
               existing_nullable=False)
    op.alter_column('test_report_upload_log', 'sys_modifier_id',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=21),
               existing_comment='修改人ID（逻辑外键关联core_user）',
               existing_nullable=True)
    op.alter_column('test_report_upload_log', 'sys_creator_id',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=21),
               existing_comment='创建人ID（逻辑外键关联core_user）',
               existing_nullable=True)
    op.alter_column('test_report_upload_log', 'id',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=21),
               existing_comment='主键ID(NanoId)',
               existing_nullable=False)
    op.alter_column('test_report_upload_log', 'testcase_block_id',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=50),
               existing_comment='用例块ID',
               existing_nullable=False)
    op.alter_column('test_report_summary', 'sys_modifier_id',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=21),
               existing_comment='修改人ID（逻辑外键关联core_user）',
               existing_nullable=True)
    op.alter_column('test_report_summary', 'sys_creator_id',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=21),
               existing_comment='创建人ID（逻辑外键关联core_user）',
               existing_nullable=True)
    op.alter_column('test_report_summary', 'id',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=21),
               existing_comment='主键ID(NanoId)',
               existing_nullable=False)
    op.alter_column('test_report_detail', 'sys_modifier_id',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=21),
               existing_comment='修改人ID（逻辑外键关联core_user）',
               existing_nullable=True)
    op.alter_column('test_report_detail', 'sys_creator_id',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=21),
               existing_comment='创建人ID（逻辑外键关联core_user）',
               existing_nullable=True)
    op.alter_column('test_report_detail', 'id',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=21),
               existing_comment='主键ID(NanoId)',
               existing_nullable=False)
    op.alter_column('test_report_detail', 'testcase_block_id',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=50),
               existing_comment='用例块ID',
               existing_nullable=False)
    op.alter_column('performance_version', 'sys_modifier_id',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='修改人ID（逻辑外键关联core_user）',
               existing_nullable=True)
    op.alter_column('performance_version', 'sys_creator_id',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='创建人ID（逻辑外键关联core_user）',
               existing_nullable=True)
    op.alter_column('performance_version', 'sys_update_datetime',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('performance_version', 'sys_create_datetime',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('performance_version', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否删除',
               existing_nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('performance_version', 'sort',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='排序',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('performance_version', 'id',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='主键ID(NanoId)',
               existing_nullable=False)
    op.alter_column('performance_version', 'is_protected',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='保护标记',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('performance_version', 'time_ranges',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='时间范围映射: {collect_id: {start, end}}',
               existing_comment='时间范围映射',
               existing_nullable=True)
    op.alter_column('performance_version', 'collect_ids',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='包含的采集记录ID列表',
               existing_nullable=False)
    op.alter_column('performance_version', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='版本名称',
               existing_nullable=False)
    op.alter_column('performance_version', 'device_id',
               existing_type=sa.String(length=21),
               type_=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='设备ID',
               existing_nullable=False)
    op.alter_column('performance_tag', 'sys_modifier_id',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='修改人ID（逻辑外键关联core_user）',
               existing_nullable=True)
    op.alter_column('performance_tag', 'sys_creator_id',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='创建人ID（逻辑外键关联core_user）',
               existing_nullable=True)
    op.alter_column('performance_tag', 'sys_update_datetime',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('performance_tag', 'sys_create_datetime',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('performance_tag', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否删除',
               existing_nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('performance_tag', 'sort',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='排序',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('performance_tag', 'id',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='主键ID(NanoId)',
               existing_nullable=False)
    op.alter_column('performance_tag', 'type',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='类型：peak/mean',
               existing_nullable=False,
               existing_server_default=sa.text("'peak'::character varying"))
    op.alter_column('performance_tag', 'duration',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='时间长度（秒）',
               existing_nullable=False)
    op.alter_column('performance_tag', 'start_relative_time',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='起始相对时间（秒）',
               existing_nullable=False)
    op.alter_column('performance_tag', 'name',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='标签名称',
               existing_nullable=False)
    op.alter_column('performance_tag', 'collect_id',
               existing_type=sa.String(length=21),
               type_=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='采集记录ID',
               existing_nullable=False)
    op.alter_column('performance_metric_mapping', 'sys_modifier_id',
               existing_type=sa.VARCHAR(length=50),
               comment='修改人ID',
               existing_comment='修改人ID（逻辑外键关联core_user）',
               existing_nullable=True)
    op.alter_column('performance_metric_mapping', 'sys_creator_id',
               existing_type=sa.VARCHAR(length=50),
               comment='创建人ID',
               existing_comment='创建人ID（逻辑外键关联core_user）',
               existing_nullable=True)
    op.alter_column('performance_marker', 'sys_modifier_id',
               existing_type=sa.VARCHAR(length=50),
               comment='修改人ID',
               existing_comment='修改人ID（逻辑外键关联core_user）',
               existing_nullable=True)
    op.alter_column('performance_marker', 'sys_creator_id',
               existing_type=sa.VARCHAR(length=50),
               comment='创建人ID',
               existing_comment='创建人ID（逻辑外键关联core_user）',
               existing_nullable=True)
    op.alter_column('performance_data', 'sys_modifier_id',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='修改人ID（逻辑外键关联core_user）',
               existing_nullable=True)
    op.alter_column('performance_data', 'sys_creator_id',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='创建人ID（逻辑外键关联core_user）',
               existing_nullable=True)
    op.alter_column('performance_data', 'sys_update_datetime',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('performance_data', 'sys_create_datetime',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('performance_data', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否删除',
               existing_nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('performance_data', 'sort',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='排序',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('performance_data', 'id',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='主键ID(NanoId)',
               existing_nullable=False)
    op.alter_column('performance_data', 'top10_gpu',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='GPU TOP10',
               existing_nullable=True)
    op.alter_column('performance_data', 'top10_cpu',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='CPU TOP10',
               existing_nullable=True)
    op.alter_column('performance_data', 'target_processes',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='目标进程数据',
               existing_nullable=True)
    op.alter_column('performance_data', 'process_handles',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='进程句柄数',
               existing_nullable=True)
    op.alter_column('performance_data', 'memory_usage',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='内存使用 GB',
               existing_nullable=True)
    op.alter_column('performance_data', 'commit_memory',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='提交内存 GB',
               existing_nullable=True)
    op.alter_column('performance_data', 'gpu_usage',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='GPU使用率 %',
               existing_nullable=True)
    op.alter_column('performance_data', 'cpu_usage',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='CPU使用率 %',
               existing_nullable=True)
    op.alter_column('performance_data', 'relative_time',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='相对时间（秒）',
               existing_nullable=False)
    op.alter_column('performance_data', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='实际时间',
               existing_nullable=False)
    op.alter_column('performance_data', 'collect_id',
               existing_type=sa.String(length=21),
               type_=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='采集记录ID',
               existing_nullable=False)
    # 删除新表（如果存在），重建旧表（使用 DateTime）
    op.execute("DROP TABLE IF EXISTS performance_compare_tag CASCADE")
    op.create_table(
        'performance_compare_tag',
        sa.Column('id', sa.String(length=50), nullable=False, primary_key=True, comment='主键ID(NanoId)'),
        sa.Column('sort', sa.Integer(), nullable=True, server_default='0', comment='排序'),
        sa.Column('is_deleted', sa.Boolean(), nullable=True, server_default='false', comment='是否删除'),
        sa.Column('sys_create_datetime', postgresql.TIMESTAMP(), nullable=True, server_default='CURRENT_TIMESTAMP', comment='创建时间'),
        sa.Column('sys_update_datetime', postgresql.TIMESTAMP(), nullable=True, server_default='CURRENT_TIMESTAMP', comment='更新时间'),
        sa.Column('sys_creator_id', sa.String(length=50), nullable=True, comment='创建人ID（逻辑外键关联core_user）'),
        sa.Column('sys_modifier_id', sa.String(length=50), nullable=True, comment='修改人ID（逻辑外键关联core_user）'),
        sa.Column('name', sa.String(length=100), nullable=False, comment='标签名称'),
        sa.Column('type', sa.String(length=20), nullable=False, server_default='peak', comment='类型: peak(冲高) / stable(稳态)'),
        sa.Column('start_time', postgresql.TIMESTAMP(), nullable=False, comment='开始时间（绝对时间，UTC）'),
        sa.Column('end_time', postgresql.TIMESTAMP(), nullable=False, comment='结束时间（绝对时间，UTC）'),
        sa.Column('note', sa.Text(), nullable=True, comment='备注'),
    )
    op.alter_column('performance_collect', 'sys_modifier_id',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='修改人ID（逻辑外键关联core_user）',
               existing_nullable=True)
    op.alter_column('performance_collect', 'sys_creator_id',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='创建人ID（逻辑外键关联core_user）',
               existing_nullable=True)
    op.alter_column('performance_collect', 'sys_update_datetime',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('performance_collect', 'sys_create_datetime',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('performance_collect', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否删除',
               existing_nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('performance_collect', 'sort',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='排序',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('performance_collect', 'id',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='主键ID(NanoId)',
               existing_nullable=False)
    op.alter_column('performance_collect', 'is_protected',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='保护标记',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('performance_collect', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='状态：running/stopped/error',
               existing_nullable=False,
               existing_server_default=sa.text("'running'::character varying"))
    op.alter_column('performance_collect', 'target_processes',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='目标进程配置',
               existing_nullable=True)
    op.alter_column('performance_collect', 'interval',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='采集频率（秒）',
               existing_nullable=False,
               existing_server_default=sa.text('5'))
    op.alter_column('performance_collect', 'end_time',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='结束时间',
               existing_nullable=True)
    op.alter_column('performance_collect', 'start_time',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='开始时间',
               existing_nullable=False)
    op.alter_column('performance_collect', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='采集名称',
               existing_nullable=True)
    op.alter_column('performance_collect', 'device_id',
               existing_type=sa.String(length=21),
               type_=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='设备ID',
               existing_nullable=False)
    op.alter_column('issues_analysis', 'sys_modifier_id',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=21),
               existing_comment='修改人ID（逻辑外键关联core_user）',
               existing_nullable=True)
    op.alter_column('issues_analysis', 'sys_creator_id',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=21),
               existing_comment='创建人ID（逻辑外键关联core_user）',
               existing_nullable=True)
    op.alter_column('issues_analysis', 'id',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=21),
               existing_comment='主键ID(NanoId)',
               existing_nullable=False)
    op.alter_column('feature_analysis', 'sys_modifier_id',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=21),
               existing_comment='修改人ID（逻辑外键关联core_user）',
               existing_nullable=True)
    op.alter_column('feature_analysis', 'sys_creator_id',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=21),
               existing_comment='创建人ID（逻辑外键关联core_user）',
               existing_nullable=True)
    op.alter_column('feature_analysis', 'id',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=21),
               existing_comment='主键ID(NanoId)',
               existing_nullable=False)
    op.alter_column('env_machine_log', 'sys_modifier_id',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=21),
               existing_comment='修改人ID（逻辑外键关联core_user）',
               existing_nullable=True)
    op.alter_column('env_machine_log', 'sys_creator_id',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=21),
               existing_comment='创建人ID（逻辑外键关联core_user）',
               existing_nullable=True)
    op.alter_column('env_machine_log', 'id',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=21),
               existing_comment='主键ID(NanoId)',
               existing_nullable=False)
    op.alter_column('env_machine', 'sys_modifier_id',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=21),
               existing_comment='修改人ID（逻辑外键关联core_user）',
               existing_nullable=True)
    op.alter_column('env_machine', 'sys_creator_id',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=21),
               existing_comment='创建人ID（逻辑外键关联core_user）',
               existing_nullable=True)
    op.alter_column('env_machine', 'id',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=21),
               existing_comment='主键ID(NanoId)',
               existing_nullable=False)
    op.alter_column('core_user', 'sys_modifier_id',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=21),
               existing_comment='修改人ID（逻辑外键关联core_user）',
               existing_nullable=True)
    op.alter_column('core_user', 'sys_creator_id',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=21),
               existing_comment='创建人ID（逻辑外键关联core_user）',
               existing_nullable=True)
    op.alter_column('core_user', 'id',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=21),
               existing_comment='主键ID(NanoId)',
               existing_nullable=False)
    op.alter_column('core_scheduler_log', 'sys_modifier_id',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=21),
               existing_comment='修改人ID（逻辑外键关联core_user）',
               existing_nullable=True)
    op.alter_column('core_scheduler_log', 'sys_creator_id',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=21),
               existing_comment='创建人ID（逻辑外键关联core_user）',
               existing_nullable=True)
    op.alter_column('core_scheduler_log', 'id',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=21),
               existing_comment='主键ID(NanoId)',
               existing_nullable=False)
    op.alter_column('core_scheduler_job', 'sys_modifier_id',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=21),
               existing_comment='修改人ID（逻辑外键关联core_user）',
               existing_nullable=True)
    op.alter_column('core_scheduler_job', 'sys_creator_id',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=21),
               existing_comment='创建人ID（逻辑外键关联core_user）',
               existing_nullable=True)
    op.alter_column('core_scheduler_job', 'id',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=21),
               existing_comment='主键ID(NanoId)',
               existing_nullable=False)
    op.alter_column('core_role_menu', 'menu_id',
               existing_type=sa.String(length=21),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('core_role_menu', 'role_id',
               existing_type=sa.String(length=21),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('core_role', 'sys_modifier_id',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=21),
               existing_comment='修改人ID（逻辑外键关联core_user）',
               existing_nullable=True)
    op.alter_column('core_role', 'sys_creator_id',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=21),
               existing_comment='创建人ID（逻辑外键关联core_user）',
               existing_nullable=True)
    op.alter_column('core_permission', 'sys_modifier_id',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=21),
               existing_comment='修改人ID（逻辑外键关联core_user）',
               existing_nullable=True)
    op.alter_column('core_permission', 'sys_creator_id',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=21),
               existing_comment='创建人ID（逻辑外键关联core_user）',
               existing_nullable=True)
    op.alter_column('core_permission', 'id',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=21),
               existing_comment='主键ID(NanoId)',
               existing_nullable=False)
    op.alter_column('core_menu', 'sys_modifier_id',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=21),
               existing_comment='修改人ID（逻辑外键关联core_user）',
               existing_nullable=True)
    op.alter_column('core_menu', 'sys_creator_id',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=21),
               existing_comment='创建人ID（逻辑外键关联core_user）',
               existing_nullable=True)
    op.alter_column('core_login_log', 'sys_modifier_id',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=21),
               existing_comment='修改人ID（逻辑外键关联core_user）',
               existing_nullable=True)
    op.alter_column('core_login_log', 'sys_creator_id',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=21),
               existing_comment='创建人ID（逻辑外键关联core_user）',
               existing_nullable=True)
    op.alter_column('core_login_log', 'id',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=21),
               existing_comment='主键ID(NanoId)',
               existing_nullable=False)
    op.alter_column('core_dept', 'sys_modifier_id',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=21),
               existing_comment='修改人ID（逻辑外键关联core_user）',
               existing_nullable=True)
    op.alter_column('core_dept', 'sys_creator_id',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=21),
               existing_comment='创建人ID（逻辑外键关联core_user）',
               existing_nullable=True)
    op.alter_column('core_dept', 'id',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=21),
               existing_comment='主键ID(NanoId)',
               existing_nullable=False)
    op.drop_index('ix_config_template_type', table_name='config_template')
    op.alter_column('config_template', 'sys_modifier_id',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=21),
               existing_comment='修改人ID（逻辑外键关联core_user）',
               existing_nullable=True)
    op.alter_column('config_template', 'sys_creator_id',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=21),
               existing_comment='创建人ID（逻辑外键关联core_user）',
               existing_nullable=True)
    op.alter_column('config_template', 'id',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=21),
               existing_comment='主键ID(NanoId)',
               existing_nullable=False)
    op.alter_column('config_template', 'config_content',
               existing_type=sa.TEXT(),
               comment='YAML配置内容',
               existing_comment='配置内容',
               existing_nullable=False)
    op.alter_column('config_template', 'type',
               existing_type=sa.VARCHAR(length=20),
               comment='模板类型: config/script',
               existing_comment='模板类型',
               existing_nullable=False,
               existing_server_default=sa.text("'config'::character varying"))
    # ### end Alembic commands ###
