"""add is_virtual field and make port nullable for virtual devices

Revision ID: 99d94b1db380
Revises: 4c7e414427f6
Create Date: 2026-05-20 23:04:37.168575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99d94b1db380'
down_revision: Union[str, None] = '4c7e414427f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Step 1: 添加 is_virtual 列为 nullable
    op.add_column('env_machine', sa.Column('is_virtual', sa.Boolean(), nullable=True, comment='是否为虚拟设备'))

    # Step 2: 更新现有数据，设置默认值 False
    op.execute("UPDATE env_machine SET is_virtual = FALSE WHERE is_virtual IS NULL")

    # Step 3: 改为 NOT NULL
    op.alter_column('env_machine', 'is_virtual', nullable=False)

    # Step 4: 修改 port 为 nullable
    op.alter_column('env_machine', 'port',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_comment='机器端口')

    # Step 5: 创建索引
    op.create_index('ix_env_machine_is_virtual', 'env_machine', ['is_virtual'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_env_machine_is_virtual', table_name='env_machine')
    op.alter_column('env_machine', 'port',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_comment='机器端口')
    op.drop_column('env_machine', 'is_virtual')
    # ### end Alembic commands ###
