"""add issues_analysis table and feature_bug_introduce field

Revision ID: 9c73a09f95db
Revises: 5dcf7cb79e39
Create Date: 2026-03-24 00:12:14.963902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c73a09f95db'
down_revision: Union[str, None] = '5dcf7cb79e39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issues_analysis',
    sa.Column('issues_id', sa.String(length=64), nullable=True, comment='问题编号'),
    sa.Column('issues_title', sa.String(length=64), nullable=True, comment='问题名称'),
    sa.Column('issues_services', sa.String(length=64), nullable=True, comment='问题归属'),
    sa.Column('issues_owner', sa.String(length=64), nullable=True, comment='开发责任人'),
    sa.Column('issues_test_owner', sa.String(length=64), nullable=True, comment='测试责任人'),
    sa.Column('issues_severity', sa.String(length=64), nullable=True, comment='严重程度'),
    sa.Column('issues_probability', sa.String(length=64), nullable=True, comment='重现概率'),
    sa.Column('issues_status', sa.String(length=64), nullable=True, comment='问题状态'),
    sa.Column('issues_version', sa.String(length=64), nullable=True, comment='发现问题版本'),
    sa.Column('feature_id', sa.String(length=64), nullable=True, comment='关联需求ID'),
    sa.Column('feature_desc', sa.String(length=64), nullable=True, comment='需求名称'),
    sa.Column('sync_time', sa.String(length=64), nullable=True, comment='数据同步时间'),
    sa.Column('create_by', sa.String(length=64), nullable=True, comment='创建者'),
    sa.Column('create_time', sa.String(length=64), nullable=True, comment='创建时间'),
    sa.Column('modify_time', sa.String(length=64), nullable=True, comment='修改时间'),
    sa.Column('id', sa.String(length=21), nullable=False, comment='主键ID(NanoId)'),
    sa.Column('sort', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='是否删除'),
    sa.Column('sys_create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('sys_update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('sys_creator_id', sa.String(length=21), nullable=True, comment='创建人ID（逻辑外键关联core_user）'),
    sa.Column('sys_modifier_id', sa.String(length=21), nullable=True, comment='修改人ID（逻辑外键关联core_user）'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_issues_deleted', 'issues_analysis', ['is_deleted'], unique=False)
    op.create_index('idx_issues_version', 'issues_analysis', ['issues_version'], unique=False)
    op.create_index(op.f('ix_issues_analysis_is_deleted'), 'issues_analysis', ['is_deleted'], unique=False)
    op.add_column('feature_analysis', sa.Column('feature_bug_introduce', sa.String(length=64), nullable=True, comment='修改引入数量'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feature_analysis', 'feature_bug_introduce')
    op.drop_index(op.f('ix_issues_analysis_is_deleted'), table_name='issues_analysis')
    op.drop_index('idx_issues_version', table_name='issues_analysis')
    op.drop_index('idx_issues_deleted', table_name='issues_analysis')
    op.drop_table('issues_analysis')
    # ### end Alembic commands ###
