"""remove task_args from scheduler_job

Revision ID: 9d3cec2e2ec1
Revises: 50c157c4ae43
Create Date: 2026-04-03 22:13:07.560086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9d3cec2e2ec1'
down_revision: Union[str, None] = '50c157c4ae43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_core_data_source_application_id', table_name='core_data_source')
    op.drop_index('ix_core_data_source_code', table_name='core_data_source')
    op.drop_index('ix_core_data_source_is_deleted', table_name='core_data_source')
    op.drop_table('core_data_source')
    op.drop_index('ix_core_dict_code', table_name='core_dict')
    op.drop_index('ix_core_dict_is_deleted', table_name='core_dict')
    op.drop_index('ix_core_dict_name', table_name='core_dict')
    op.drop_index('ix_core_dict_status', table_name='core_dict')
    op.drop_table('core_dict')
    op.drop_index('ix_announcement_read_unique', table_name='core_announcement_read')
    op.drop_index('ix_core_announcement_read_announcement_id', table_name='core_announcement_read')
    op.drop_index('ix_core_announcement_read_is_deleted', table_name='core_announcement_read')
    op.drop_index('ix_core_announcement_read_user_id', table_name='core_announcement_read')
    op.drop_table('core_announcement_read')
    op.drop_index('ix_demos_is_deleted', table_name='demos')
    op.drop_table('demos')
    op.drop_index('ix_core_dict_item_dict_id', table_name='core_dict_item')
    op.drop_index('ix_core_dict_item_is_deleted', table_name='core_dict_item')
    op.drop_index('ix_core_dict_item_label', table_name='core_dict_item')
    op.drop_index('ix_core_dict_item_status', table_name='core_dict_item')
    op.drop_index('ix_core_dict_item_value', table_name='core_dict_item')
    op.drop_table('core_dict_item')
    op.drop_index('ix_demo_cache_is_deleted', table_name='demo_cache')
    op.drop_index('ix_demo_cache_title', table_name='demo_cache')
    op.drop_table('demo_cache')
    op.drop_index('ix_page_meta_is_deleted', table_name='page_meta')
    op.drop_index('ix_page_meta_status', table_name='page_meta')
    op.drop_table('page_meta')
    op.drop_index('ix_core_announcement_is_deleted', table_name='core_announcement')
    op.drop_index('ix_core_announcement_priority', table_name='core_announcement')
    op.drop_index('ix_core_announcement_status', table_name='core_announcement')
    op.drop_table('core_announcement')
    op.alter_column('core_scheduler_job', 'task_kwargs',
               existing_type=sa.TEXT(),
               comment='任务参数（JSON格式）',
               existing_comment='任务关键字参数（JSON对象格式）',
               existing_nullable=True)
    op.drop_column('core_scheduler_job', 'task_args')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('core_scheduler_job', sa.Column('task_args', sa.TEXT(), autoincrement=False, nullable=True, comment='任务位置参数（JSON数组格式）'))
    op.alter_column('core_scheduler_job', 'task_kwargs',
               existing_type=sa.TEXT(),
               comment='任务关键字参数（JSON对象格式）',
               existing_comment='任务参数（JSON格式）',
               existing_nullable=True)
    op.create_table('core_announcement',
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False, comment='公告标题'),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False, comment='公告内容'),
    sa.Column('summary', sa.VARCHAR(length=500), autoincrement=False, nullable=True, comment='摘要'),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True, comment='状态: draft/published/expired'),
    sa.Column('priority', sa.INTEGER(), autoincrement=False, nullable=True, comment='优先级: 0普通/1重要/2紧急'),
    sa.Column('is_top', sa.BOOLEAN(), autoincrement=False, nullable=True, comment='是否置顶'),
    sa.Column('target_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True, comment='接收范围类型: all/dept/role/user'),
    sa.Column('target_ids', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='接收目标ID列表'),
    sa.Column('publish_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True, comment='发布时间'),
    sa.Column('expire_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True, comment='过期时间'),
    sa.Column('publisher_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment='发布人ID'),
    sa.Column('read_count', sa.INTEGER(), autoincrement=False, nullable=True, comment='阅读次数'),
    sa.Column('id', sa.VARCHAR(length=21), autoincrement=False, nullable=False, comment='主键ID(NanoId)'),
    sa.Column('sort', sa.INTEGER(), autoincrement=False, nullable=True, comment='排序'),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True, comment='是否删除'),
    sa.Column('sys_create_datetime', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True, comment='创建时间'),
    sa.Column('sys_update_datetime', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True, comment='更新时间'),
    sa.Column('sys_creator_id', sa.VARCHAR(length=21), autoincrement=False, nullable=True, comment='创建人ID（逻辑外键关联core_user）'),
    sa.Column('sys_modifier_id', sa.VARCHAR(length=21), autoincrement=False, nullable=True, comment='修改人ID（逻辑外键关联core_user）'),
    sa.PrimaryKeyConstraint('id', name='core_announcement_pkey')
    )
    op.create_index('ix_core_announcement_status', 'core_announcement', ['status'], unique=False)
    op.create_index('ix_core_announcement_priority', 'core_announcement', ['priority'], unique=False)
    op.create_index('ix_core_announcement_is_deleted', 'core_announcement', ['is_deleted'], unique=False)
    op.create_table('page_meta',
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False, comment='页面名称'),
    sa.Column('code', sa.VARCHAR(length=100), autoincrement=False, nullable=False, comment='页面编码'),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment='分类'),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True, comment='描述'),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True, comment='状态: draft/published'),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=True, comment='版本号'),
    sa.Column('page_config', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='页面设计配置'),
    sa.Column('id', sa.VARCHAR(length=21), autoincrement=False, nullable=False, comment='主键ID(NanoId)'),
    sa.Column('sort', sa.INTEGER(), autoincrement=False, nullable=True, comment='排序'),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True, comment='是否删除'),
    sa.Column('sys_create_datetime', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True, comment='创建时间'),
    sa.Column('sys_update_datetime', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True, comment='更新时间'),
    sa.Column('sys_creator_id', sa.VARCHAR(length=21), autoincrement=False, nullable=True, comment='创建人ID（逻辑外键关联core_user）'),
    sa.Column('sys_modifier_id', sa.VARCHAR(length=21), autoincrement=False, nullable=True, comment='修改人ID（逻辑外键关联core_user）'),
    sa.PrimaryKeyConstraint('id', name='page_meta_pkey'),
    sa.UniqueConstraint('code', name='page_meta_code_key')
    )
    op.create_index('ix_page_meta_status', 'page_meta', ['status'], unique=False)
    op.create_index('ix_page_meta_is_deleted', 'page_meta', ['is_deleted'], unique=False)
    op.create_table('demo_cache',
    sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=False, comment='标题'),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True, comment='内容'),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True, comment='是否激活'),
    sa.Column('id', sa.VARCHAR(length=21), autoincrement=False, nullable=False, comment='主键ID(NanoId)'),
    sa.Column('sort', sa.INTEGER(), autoincrement=False, nullable=True, comment='排序'),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True, comment='是否删除'),
    sa.Column('sys_create_datetime', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True, comment='创建时间'),
    sa.Column('sys_update_datetime', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True, comment='更新时间'),
    sa.Column('sys_creator_id', sa.VARCHAR(length=21), autoincrement=False, nullable=True, comment='创建人ID（逻辑外键关联core_user）'),
    sa.Column('sys_modifier_id', sa.VARCHAR(length=21), autoincrement=False, nullable=True, comment='修改人ID（逻辑外键关联core_user）'),
    sa.PrimaryKeyConstraint('id', name='demo_cache_pkey')
    )
    op.create_index('ix_demo_cache_title', 'demo_cache', ['title'], unique=False)
    op.create_index('ix_demo_cache_is_deleted', 'demo_cache', ['is_deleted'], unique=False)
    op.create_table('core_dict_item',
    sa.Column('dict_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False, comment='字典ID'),
    sa.Column('label', sa.VARCHAR(length=100), autoincrement=False, nullable=True, comment='显示名称'),
    sa.Column('value', sa.VARCHAR(length=100), autoincrement=False, nullable=True, comment='实际值'),
    sa.Column('icon', sa.VARCHAR(length=100), autoincrement=False, nullable=True, comment='图标'),
    sa.Column('status', sa.BOOLEAN(), autoincrement=False, nullable=True, comment='状态'),
    sa.Column('remark', sa.TEXT(), autoincrement=False, nullable=True, comment='备注'),
    sa.Column('id', sa.VARCHAR(length=21), autoincrement=False, nullable=False, comment='主键ID(NanoId)'),
    sa.Column('sort', sa.INTEGER(), autoincrement=False, nullable=True, comment='排序'),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True, comment='是否删除'),
    sa.Column('sys_create_datetime', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True, comment='创建时间'),
    sa.Column('sys_update_datetime', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True, comment='更新时间'),
    sa.Column('sys_creator_id', sa.VARCHAR(length=21), autoincrement=False, nullable=True, comment='创建人ID（逻辑外键关联core_user）'),
    sa.Column('sys_modifier_id', sa.VARCHAR(length=21), autoincrement=False, nullable=True, comment='修改人ID（逻辑外键关联core_user）'),
    sa.PrimaryKeyConstraint('id', name='core_dict_item_pkey')
    )
    op.create_index('ix_core_dict_item_value', 'core_dict_item', ['value'], unique=False)
    op.create_index('ix_core_dict_item_status', 'core_dict_item', ['status'], unique=False)
    op.create_index('ix_core_dict_item_label', 'core_dict_item', ['label'], unique=False)
    op.create_index('ix_core_dict_item_is_deleted', 'core_dict_item', ['is_deleted'], unique=False)
    op.create_index('ix_core_dict_item_dict_id', 'core_dict_item', ['dict_id'], unique=False)
    op.create_table('demos',
    sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=False, comment='标题'),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True, comment='内容'),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True, comment='是否激活'),
    sa.Column('id', sa.VARCHAR(length=21), autoincrement=False, nullable=False, comment='主键ID(NanoId)'),
    sa.Column('sort', sa.INTEGER(), autoincrement=False, nullable=True, comment='排序'),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True, comment='是否删除'),
    sa.Column('sys_create_datetime', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True, comment='创建时间'),
    sa.Column('sys_update_datetime', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True, comment='更新时间'),
    sa.Column('sys_creator_id', sa.VARCHAR(length=21), autoincrement=False, nullable=True, comment='创建人ID（逻辑外键关联core_user）'),
    sa.Column('sys_modifier_id', sa.VARCHAR(length=21), autoincrement=False, nullable=True, comment='修改人ID（逻辑外键关联core_user）'),
    sa.PrimaryKeyConstraint('id', name='demos_pkey')
    )
    op.create_index('ix_demos_is_deleted', 'demos', ['is_deleted'], unique=False)
    op.create_table('core_announcement_read',
    sa.Column('announcement_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment='公告ID'),
    sa.Column('user_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment='用户ID'),
    sa.Column('read_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True, comment='阅读时间'),
    sa.Column('id', sa.VARCHAR(length=21), autoincrement=False, nullable=False, comment='主键ID(NanoId)'),
    sa.Column('sort', sa.INTEGER(), autoincrement=False, nullable=True, comment='排序'),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True, comment='是否删除'),
    sa.Column('sys_create_datetime', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True, comment='创建时间'),
    sa.Column('sys_update_datetime', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True, comment='更新时间'),
    sa.Column('sys_creator_id', sa.VARCHAR(length=21), autoincrement=False, nullable=True, comment='创建人ID（逻辑外键关联core_user）'),
    sa.Column('sys_modifier_id', sa.VARCHAR(length=21), autoincrement=False, nullable=True, comment='修改人ID（逻辑外键关联core_user）'),
    sa.PrimaryKeyConstraint('id', name='core_announcement_read_pkey')
    )
    op.create_index('ix_core_announcement_read_user_id', 'core_announcement_read', ['user_id'], unique=False)
    op.create_index('ix_core_announcement_read_is_deleted', 'core_announcement_read', ['is_deleted'], unique=False)
    op.create_index('ix_core_announcement_read_announcement_id', 'core_announcement_read', ['announcement_id'], unique=False)
    op.create_index('ix_announcement_read_unique', 'core_announcement_read', ['announcement_id', 'user_id'], unique=False)
    op.create_table('core_dict',
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False, comment='字典名称'),
    sa.Column('code', sa.VARCHAR(length=100), autoincrement=False, nullable=False, comment='字典编码'),
    sa.Column('status', sa.BOOLEAN(), autoincrement=False, nullable=True, comment='状态'),
    sa.Column('remark', sa.TEXT(), autoincrement=False, nullable=True, comment='备注'),
    sa.Column('id', sa.VARCHAR(length=21), autoincrement=False, nullable=False, comment='主键ID(NanoId)'),
    sa.Column('sort', sa.INTEGER(), autoincrement=False, nullable=True, comment='排序'),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True, comment='是否删除'),
    sa.Column('sys_create_datetime', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True, comment='创建时间'),
    sa.Column('sys_update_datetime', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True, comment='更新时间'),
    sa.Column('sys_creator_id', sa.VARCHAR(length=21), autoincrement=False, nullable=True, comment='创建人ID（逻辑外键关联core_user）'),
    sa.Column('sys_modifier_id', sa.VARCHAR(length=21), autoincrement=False, nullable=True, comment='修改人ID（逻辑外键关联core_user）'),
    sa.PrimaryKeyConstraint('id', name='core_dict_pkey')
    )
    op.create_index('ix_core_dict_status', 'core_dict', ['status'], unique=False)
    op.create_index('ix_core_dict_name', 'core_dict', ['name'], unique=False)
    op.create_index('ix_core_dict_is_deleted', 'core_dict', ['is_deleted'], unique=False)
    op.create_index('ix_core_dict_code', 'core_dict', ['code'], unique=False)
    op.create_table('core_data_source',
    sa.Column('application_id', sa.VARCHAR(length=21), autoincrement=False, nullable=True, comment='所属应用ID'),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False, comment='数据源名称'),
    sa.Column('code', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment='数据源编码（唯一标识）'),
    sa.Column('source_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True, comment='数据源类型: api/sql/static'),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True, comment='描述说明'),
    sa.Column('status', sa.BOOLEAN(), autoincrement=False, nullable=True, comment='是否启用'),
    sa.Column('api_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True, comment='API地址，支持 {param} 占位符'),
    sa.Column('api_method', sa.VARCHAR(length=10), autoincrement=False, nullable=True, comment='请求方法: GET/POST'),
    sa.Column('api_headers', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='请求头配置'),
    sa.Column('api_body', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='请求体模板（POST 时使用）'),
    sa.Column('api_timeout', sa.INTEGER(), autoincrement=False, nullable=True, comment='请求超时时间（秒）'),
    sa.Column('api_data_path', sa.VARCHAR(length=100), autoincrement=False, nullable=True, comment='响应数据路径，如 data.list'),
    sa.Column('sql_content', sa.TEXT(), autoincrement=False, nullable=True, comment='SQL语句，使用 :param 作为参数占位符'),
    sa.Column('db_connection', sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment='数据库连接名称'),
    sa.Column('static_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='静态数据（JSON 数组）'),
    sa.Column('params', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='参数定义列表'),
    sa.Column('result_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True, comment='结果类型: list/tree/object/value/chart-*'),
    sa.Column('tree_config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='树形转换配置'),
    sa.Column('field_mapping', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='字段映射配置'),
    sa.Column('chart_config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='图表配置'),
    sa.Column('cache_enabled', sa.BOOLEAN(), autoincrement=False, nullable=True, comment='是否启用缓存'),
    sa.Column('cache_ttl', sa.INTEGER(), autoincrement=False, nullable=True, comment='缓存时间（秒）'),
    sa.Column('id', sa.VARCHAR(length=21), autoincrement=False, nullable=False, comment='主键ID(NanoId)'),
    sa.Column('sort', sa.INTEGER(), autoincrement=False, nullable=True, comment='排序'),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True, comment='是否删除'),
    sa.Column('sys_create_datetime', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True, comment='创建时间'),
    sa.Column('sys_update_datetime', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True, comment='更新时间'),
    sa.Column('sys_creator_id', sa.VARCHAR(length=21), autoincrement=False, nullable=True, comment='创建人ID（逻辑外键关联core_user）'),
    sa.Column('sys_modifier_id', sa.VARCHAR(length=21), autoincrement=False, nullable=True, comment='修改人ID（逻辑外键关联core_user）'),
    sa.PrimaryKeyConstraint('id', name='core_data_source_pkey')
    )
    op.create_index('ix_core_data_source_is_deleted', 'core_data_source', ['is_deleted'], unique=False)
    op.create_index('ix_core_data_source_code', 'core_data_source', ['code'], unique=False)
    op.create_index('ix_core_data_source_application_id', 'core_data_source', ['application_id'], unique=False)
    # ### end Alembic commands ###
