"""add env_machine_log table

Revision ID: a1b2c3d4e5f6
Revises: 3c0071924a91
Create Date: 2026-04-04 15:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f6'
down_revision: Union[str, None] = '3c0071924a91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('env_machine_log',
    sa.Column('namespace', sa.String(length=64), nullable=False, comment='机器分类'),
    sa.Column('machine_id', sa.String(length=36), nullable=False, comment='机器ID'),
    sa.Column('ip', sa.String(length=45), nullable=True, comment='机器IP'),
    sa.Column('device_type', sa.String(length=20), nullable=False, comment='机器类型'),
    sa.Column('device_sn', sa.String(length=64), nullable=True, comment='设备SN'),
    sa.Column('mark', sa.String(length=255), nullable=True, comment='申请的标签'),
    sa.Column('action', sa.String(length=20), nullable=False, comment='操作类型: apply/release'),
    sa.Column('result', sa.String(length=20), nullable=False, comment='结果: success/fail'),
    sa.Column('fail_reason', sa.String(length=255), nullable=True, comment='失败原因'),
    sa.Column('apply_time', sa.DateTime(), nullable=True, comment='申请时间'),
    sa.Column('release_time', sa.DateTime(), nullable=True, comment='释放时间'),
    sa.Column('duration_minutes', sa.Integer(), nullable=True, comment='占用时长（分钟）'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='主键ID(UUID)'),
    sa.Column('sort', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='是否删除'),
    sa.Column('sys_create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('sys_update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('sys_creator_id', sa.String(length=36), nullable=True, comment='创建人ID'),
    sa.Column('sys_modifier_id', sa.String(length=36), nullable=True, comment='修改人ID'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_env_machine_log_create_time', 'env_machine_log', ['sys_create_datetime'], unique=False)
    op.create_index('ix_env_machine_log_namespace_time', 'env_machine_log', ['namespace', 'sys_create_datetime'], unique=False)
    op.create_index('ix_env_machine_log_machine_id', 'env_machine_log', ['machine_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_env_machine_log_machine_id', table_name='env_machine_log')
    op.drop_index('ix_env_machine_log_namespace_time', table_name='env_machine_log')
    op.drop_index('ix_env_machine_log_create_time', table_name='env_machine_log')
    op.drop_table('env_machine_log')
    # ### end Alembic commands ###