"""add profile fields to ai_assistant_message

Revision ID: a1b2c3d4e5f7
Revises: d70dec55a9b5
Create Date: 2026-04-13 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f7'
down_revision: Union[str, None] = 'd70dec55a9b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 为 ai_assistant_message 表添加多角色群组的角色信息字段
    op.add_column('ai_assistant_message', sa.Column('profile_id', sa.String(length=100), nullable=True, comment='角色ID（多角色群组时有效）'))
    op.add_column('ai_assistant_message', sa.Column('profile_name', sa.String(length=100), nullable=True, comment='角色显示名称（多角色群组时有效）'))
    op.add_column('ai_assistant_message', sa.Column('trigger_word', sa.String(length=50), nullable=True, comment='触发词（多角色群组时有效）'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_assistant_message', 'trigger_word')
    op.drop_column('ai_assistant_message', 'profile_name')
    op.drop_column('ai_assistant_message', 'profile_id')
    # ### end Alembic commands ###