"""add export_task table

Revision ID: a88d9b9c688b
Revises: 95c464f48885
Create Date: 2026-05-17 20:17:05.943492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a88d9b9c688b'
down_revision: Union[str, None] = '95c464f48885'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('export_task',
    sa.Column('task_type', sa.String(length=50), nullable=False, comment='任务类型'),
    sa.Column('params', sa.JSON(), nullable=False, comment='任务参数'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态'),
    sa.Column('progress', sa.Integer(), nullable=False, comment='进度（0-100）'),
    sa.Column('message', sa.String(length=500), nullable=True, comment='进度消息'),
    sa.Column('file_path', sa.String(length=500), nullable=True, comment='文件路径'),
    sa.Column('completed_at', sa.DateTime(), nullable=True, comment='完成时间'),
    sa.Column('id', sa.String(length=50), nullable=False, comment='主键ID(NanoId)'),
    sa.Column('sort', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='是否删除'),
    sa.Column('sys_create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('sys_update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('sys_creator_id', sa.String(length=50), nullable=True, comment='创建人ID（逻辑外键关联core_user）'),
    sa.Column('sys_modifier_id', sa.String(length=50), nullable=True, comment='修改人ID（逻辑外键关联core_user）'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_export_task_is_deleted'), 'export_task', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_export_task_status'), 'export_task', ['status'], unique=False)
    op.create_index(op.f('ix_export_task_task_type'), 'export_task', ['task_type'], unique=False)
    op.alter_column('performance_compare_tag', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment='标签名称',
               existing_nullable=False)
    op.alter_column('performance_compare_tag', 'type',
               existing_type=sa.VARCHAR(length=20),
               comment='类型: peak(冲高) / stable(稳态)',
               existing_nullable=False,
               existing_server_default=sa.text("'peak'::character varying"))
    op.alter_column('performance_compare_tag', 'start_time',
               existing_type=sa.INTEGER(),
               comment='开始时间（相对秒数）',
               existing_nullable=False)
    op.alter_column('performance_compare_tag', 'end_time',
               existing_type=sa.INTEGER(),
               comment='结束时间（相对秒数）',
               existing_nullable=False)
    op.alter_column('performance_compare_tag', 'note',
               existing_type=sa.TEXT(),
               comment='备注',
               existing_nullable=True)
    op.alter_column('performance_compare_tag', 'id',
               existing_type=sa.VARCHAR(length=50),
               comment='主键ID(NanoId)',
               existing_nullable=False)
    op.alter_column('performance_compare_tag', 'sort',
               existing_type=sa.INTEGER(),
               comment='排序',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('performance_compare_tag', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               comment='是否删除',
               existing_nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('performance_compare_tag', 'sys_create_datetime',
               existing_type=postgresql.TIMESTAMP(),
               comment='创建时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('performance_compare_tag', 'sys_update_datetime',
               existing_type=postgresql.TIMESTAMP(),
               comment='更新时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('performance_compare_tag', 'sys_creator_id',
               existing_type=sa.VARCHAR(length=50),
               comment='创建人ID（逻辑外键关联core_user）',
               existing_nullable=True)
    op.alter_column('performance_compare_tag', 'sys_modifier_id',
               existing_type=sa.VARCHAR(length=50),
               comment='修改人ID（逻辑外键关联core_user）',
               existing_nullable=True)
    op.create_index(op.f('ix_performance_compare_tag_is_deleted'), 'performance_compare_tag', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_performance_compare_tag_is_deleted'), table_name='performance_compare_tag')
    op.alter_column('performance_compare_tag', 'sys_modifier_id',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='修改人ID（逻辑外键关联core_user）',
               existing_nullable=True)
    op.alter_column('performance_compare_tag', 'sys_creator_id',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='创建人ID（逻辑外键关联core_user）',
               existing_nullable=True)
    op.alter_column('performance_compare_tag', 'sys_update_datetime',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('performance_compare_tag', 'sys_create_datetime',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('performance_compare_tag', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否删除',
               existing_nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('performance_compare_tag', 'sort',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='排序',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('performance_compare_tag', 'id',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='主键ID(NanoId)',
               existing_nullable=False)
    op.alter_column('performance_compare_tag', 'note',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='备注',
               existing_nullable=True)
    op.alter_column('performance_compare_tag', 'end_time',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='结束时间（相对秒数）',
               existing_nullable=False)
    op.alter_column('performance_compare_tag', 'start_time',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='开始时间（相对秒数）',
               existing_nullable=False)
    op.alter_column('performance_compare_tag', 'type',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='类型: peak(冲高) / stable(稳态)',
               existing_nullable=False,
               existing_server_default=sa.text("'peak'::character varying"))
    op.alter_column('performance_compare_tag', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='标签名称',
               existing_nullable=False)
    op.drop_index(op.f('ix_export_task_task_type'), table_name='export_task')
    op.drop_index(op.f('ix_export_task_status'), table_name='export_task')
    op.drop_index(op.f('ix_export_task_is_deleted'), table_name='export_task')
    op.drop_table('export_task')
    # ### end Alembic commands ###
