"""make fail_reason, testcase_block_id, fail_time required

Revision ID: cb76b93485bf
Revises: 96da0848eb60
Create Date: 2026-04-08 01:22:11.059299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cb76b93485bf'
down_revision: Union[str, None] = '96da0848eb60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('test_report_detail', 'fail_reason',
               existing_type=sa.VARCHAR(length=500),
               nullable=False,
               existing_comment='失败原因')
    op.alter_column('test_report_detail', 'testcase_block_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_comment='用例块ID')
    op.alter_column('test_report_detail', 'fail_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_comment='失败时间')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('test_report_detail', 'fail_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_comment='失败时间')
    op.alter_column('test_report_detail', 'testcase_block_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_comment='用例块ID')
    op.alter_column('test_report_detail', 'fail_reason',
               existing_type=sa.VARCHAR(length=500),
               nullable=True,
               existing_comment='失败原因')
    # ### end Alembic commands ###
