"""rename code to role_id and make nullable

Revision ID: d70dec55a9b5
Revises: 11e42496ca4c
Create Date: 2026-04-13 00:47:24.875434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd70dec55a9b5'
down_revision: Union[str, None] = '11e42496ca4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_assistant_role', sa.Column('role_id', sa.String(length=50), nullable=True, comment='角色ID'))
    op.drop_index('ix_ai_assistant_role_code', table_name='ai_assistant_role')
    op.create_index(op.f('ix_ai_assistant_role_role_id'), 'ai_assistant_role', ['role_id'], unique=True)
    op.drop_column('ai_assistant_role', 'code')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_assistant_role', sa.Column('code', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment='角色编码'))
    op.drop_index(op.f('ix_ai_assistant_role_role_id'), table_name='ai_assistant_role')
    op.create_index('ix_ai_assistant_role_code', 'ai_assistant_role', ['code'], unique=False)
    op.drop_column('ai_assistant_role', 'role_id')
    # ### end Alembic commands ###
