"""add fail_reason to test_report_detail

Revision ID: d8f91258f2b0
Revises: 20260404_source_pool
Create Date: 2026-04-05 16:05:02.123114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8f91258f2b0'
down_revision: Union[str, None] = '20260404_source_pool'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('env_machine_log', 'id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=21),
               comment='主键ID(NanoId)',
               existing_comment='主键ID(UUID)',
               existing_nullable=False)
    op.alter_column('env_machine_log', 'sys_creator_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=21),
               comment='创建人ID（逻辑外键关联core_user）',
               existing_comment='创建人ID',
               existing_nullable=True)
    op.alter_column('env_machine_log', 'sys_modifier_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=21),
               comment='修改人ID（逻辑外键关联core_user）',
               existing_comment='修改人ID',
               existing_nullable=True)
    op.create_index(op.f('ix_env_machine_log_is_deleted'), 'env_machine_log', ['is_deleted'], unique=False)
    op.add_column('test_report_detail', sa.Column('fail_reason', sa.String(length=500), nullable=True, comment='失败原因'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_report_detail', 'fail_reason')
    op.drop_index(op.f('ix_env_machine_log_is_deleted'), table_name='env_machine_log')
    op.alter_column('env_machine_log', 'sys_modifier_id',
               existing_type=sa.String(length=21),
               type_=sa.VARCHAR(length=36),
               comment='修改人ID',
               existing_comment='修改人ID（逻辑外键关联core_user）',
               existing_nullable=True)
    op.alter_column('env_machine_log', 'sys_creator_id',
               existing_type=sa.String(length=21),
               type_=sa.VARCHAR(length=36),
               comment='创建人ID',
               existing_comment='创建人ID（逻辑外键关联core_user）',
               existing_nullable=True)
    op.alter_column('env_machine_log', 'id',
               existing_type=sa.String(length=21),
               type_=sa.VARCHAR(length=36),
               comment='主键ID(UUID)',
               existing_comment='主键ID(NanoId)',
               existing_nullable=False)
    # ### end Alembic commands ###
